### ISSUE TITLE
Rendering underwater is incorrect

### ISSUE THREAD

**Issue by Altirix** [MCRcortex/nvidium#10]
![image](https://user-images.githubusercontent.com/19439141/234139874-45f81b9d-d4b0-4705-828e-0b83c8e603aa.png)

there is no fog or blue effect when underwater, rather it is applied to entities

**Comment by Altirix** [comment]
also noticed flying thru coral ( i assume anything that is cutout i assume as seagrass did it aswell.) causes the chunk culling to be too aggressive and there's also a lot of flickering from that.

**Comment by MCRcortex** [comment]
does it stop flickering once you stand still?

**Comment by Altirix** [comment]
> does it stop flickering once you stand still?

yeah only occurs when you are moving around them.

**Comment by MCRcortex** [comment]
Fixed in https://github.com/MCRcortex/nvidium/commit/1312a14080a6496c91705ea2cdf8dc22265b4747
