### ISSUE TITLE
[Request] Provide Valid Downloads

### ISSUE THREAD

**Issue by gudenau** [MCRcortex/nvidium#100]
It would be nice if you had valid downloads for this mod, at least GitHub releases and Curse Forge would be highly appreciated. I can build from source, but I shouldn't have to.

**Comment by TH3N3WN00B** [comment]
Like this: https://modrinth.com/mod/nvidium?

**Comment by gudenau** [comment]
Not Modrinth, something reasonable like Curse Forge or Github releases.

**Comment by TH3N3WN00B** [comment]
> Not Modrinth, something reasonable like Curse Forge or Github releases.

what is wrong with modrinth?

**Comment by sheikh1233** [comment]
> Not Modrinth, something reasonable like Curse Forge or Github releases.

is there something wrong with it?
why do you call modrinth unreasonable?

**Comment by gudenau** [comment]
> > Not Modrinth, something reasonable like Curse Forge or Github releases.
> 
> what is wrong with modrinth?



> > Not Modrinth, something reasonable like Curse Forge or Github releases.
> 
> is there something wrong with it? why do you call modrinth unreasonable?



> > Not Modrinth, something reasonable like Curse Forge or Github releases.
> 
> what is wrong with modrinth?

> > Not Modrinth, something reasonable like Curse Forge or Github releases.
> 
> what is wrong with modrinth?



> > Not Modrinth, something reasonable like Curse Forge or Github releases.
> 
> is there something wrong with it? why do you call modrinth unreasonable?

Yes they have but that's not stuff to bring up here.

**Comment by TH3N3WN00B** [comment]
Well, thats the only download link for the moment like it or not, but feel free to fork this and build it yourself 😄

**Comment by Bjorkan** [comment]
I can buy that it might be annoying not to can have it in a modpack if it not on Curseforge but other than that, Modrinth seems more than acceptable and an Open Source alternative to CurseForge

**Comment by gudenau** [comment]
> I can buy that it might be annoying not to can have it in a modpack if it not on Curseforge but other than that, Modrinth seems more than acceptable and an Open Source alternative to CurseForge.
> 
> But that doesn't in any way make Modrinth "unreasonable"

It's not because you can't use it with their modpacks, again it's not a reasonable topic for this issue.

But clearly it's not going to happen so I'll close this.

**Comment by Xplodin** [comment]
Greed, that is why its not on Curseforge. Modrinth pays better.
They also dont want you to use this mod in modpacks on CF whether its greed or simply its beta
