### ISSUE TITLE
1.18.2 port

### ISSUE THREAD

**Issue by Fefedu973** [MCRcortex/nvidium#102]

**Comment by ZARAEM** [comment]
+1

**Comment by Benisgo** [comment]
+1

**Comment by lydonator** [comment]
+1

**Comment by W4BEPMA** [comment]
+1

**Comment by KarmaMarazu** [comment]
![hey_buddy](https://github.com/MCRcortex/nvidium/assets/98053409/8aae6594-7f3d-45a8-a867-6cb1871dbc26)
1.18.2 will only happen if sodium 0.5.3/5/8 gets ported
