### ISSUE TITLE
Minecraft Runs Slower After Uninstalling.

### ISSUE THREAD

**Issue by fixitpleeze** [MCRcortex/nvidium#104]
My friend uninstalled Nvidium because he didn't want it, and now his Minecraft runs 2x slower! Both him and me don't know what's wrong. He has an Nvidium-compatible GPU, he's deleted all related files, but it still runs really slow. Anyone know what could be wrong?

**Comment by sheikh1233** [comment]
did it run that slow before nvidium?

**Comment by fixitpleeze** [comment]
> did it run that slow before nvidium?
No, it's a pretty nice laptop, and it ran minecraft at 200+ FPS, it ran 300+ FPS with nvidium, but he uninstalled it because he wanted shaders, but after uninstalling nvidium, minecraft runs at only 70-80 FPS, and he didn't change anything besides Nvidium. Quite a pickle.

**Comment by Sierraint** [comment]
> > did it run that slow before nvidium?
> > No, it's a pretty nice laptop
> Could it be that the laptop decided to prioritize   iGPU instead of dGPU in the laptop

**Comment by NoahAdrian** [comment]
Hello, I am the "friend" who's minecraft runs like sh*t. I have a Lenovo Idea Gaming 3 with a Nvidia 3050ti gpu and a Ryzen 5000-5 cpu. I ran minecraft at a maximum of around 250 fps with rtx shaders and texture packs. I heard that nvidium can significantly increase minecraft's performance, so I decided to try it. I uninstalled iris shaders and downloaded nvidium in its place. It ran wonderfully, but I decided later that I wanted to go back to my pretty minecraft with shders and texture packs that ran just as good as with nvidium. I then installed nvidium and all related files, reinstalled iris shaders with the same shaders and texture packs, but now my minecraft runs at a maximum of 80 fps. I did not change any settings, my framerates are uncapped, minecraft it still utilizing my high power Nvidia gpu, and every performance enhancing mod I had previously is still there. On top of this, I recently added distant horizons & indium, which further decreased my performance. I am completely lost. Everything should be the same as ot was, but it is not. I appreciate any help that you all may provide. I can also send a list of all of the mods I use if someone needs it. Thank you

**Comment by Sierraint** [comment]
>   now my minecraft runs at a maximum of 80 fps. I did not change any settings, my framerates are uncapped, minecraft it still >utilizing my high power Nvidia gpu 
This could mean a possible CPU bottleneck but since you had 250 fps before it also could be cpu throttling, that is if you are getting only 80fps without shaders

**Comment by NoahAdrian** [comment]
I had 250 maximum fps with all the mods, shaders, and texture packs as I currently do. Then, I installed nvidium and got rid of my shaders, my texture packs, and the iris shader mod and got 300+ fps. After, I deleted nvidium, redownloaded all the mods, shaders, and texture packs I used previously, but I only get a maximum of 80 fps. Everything is the exact same as before (or, I at least have the exact same assets as before), yet my performance is tanked.

**Comment by ferriarnus** [comment]
Did you change in game settings like chunk distance?

**Comment by NoahAdrian** [comment]
Yes, I have my render distance set to 12 instead of 16, which is what it was previously set as when my minecraft actually worked.

**Comment by NoahAdrian** [comment]
This is the list of minecraft mods that used before I installed Nvidium and the mods I currently use; https://docs.google.com/spreadsheets/d/1nfOF18OkQCZSu3rLAQlu6UQbCv0XQVJuCY68zf3xFIE/edit?usp=sharing
