### ISSUE TITLE
chunks stop being displayed on a large rendering if you look at the top or behind the objects

### ISSUE THREAD

**Issue by TheKveilan** [MCRcortex/nvidium#105]
![2023-11-21_13 50 46](https://github.com/MCRcortex/nvidium/assets/151543343/57334612-c618-4745-8084-0f05bbc08033)
![2023-11-21_13 50 52](https://github.com/MCRcortex/nvidium/assets/151543343/4ff47477-7af4-42c9-af91-7eac1e66dd08)
![2023-11-21_13 50 55](https://github.com/MCRcortex/nvidium/assets/151543343/ad56a49a-143a-474a-b6f3-eb6236475693)
![2023-11-21_13 50 58](https://github.com/MCRcortex/nvidium/assets/151543343/849bea96-6222-469e-bfe2-29b5b8fae3a3)
![2023-11-21_13 52 09](https://github.com/MCRcortex/nvidium/assets/151543343/0045ee75-5bdd-4e6a-a87b-a6f5eebcbcde)
![2023-11-21_13 52 46](https://github.com/MCRcortex/nvidium/assets/151543343/d4af0400-9879-45e4-80f5-ed55236c105d)
![2023-11-21_14 23 32](https://github.com/MCRcortex/nvidium/assets/151543343/cde54935-216f-4c2c-9a36-15a6b4ec1eba)
chunks are no longer displayed on a large rendering behind some objects such as mountains
reloading chunks helps

I think it has something to do with culling

**Comment by MCRcortex** [comment]
Your gpu memory is full and nvidium has to unload terrain in order to keep the game from running out of memory and crashing, you can change the limit to manual and increase the memory limit but this has risk of huge performance drops and possible crashes
