### ISSUE TITLE
Chunk rendering breaks when you get in the millions.

### ISSUE THREAD

**Issue by Ikstoi** [MCRcortex/nvidium#107]
The chunk render completely stops when you get past 8,388,608 blocks.
![2023-12-02_11 04 47](https://github.com/MCRcortex/nvidium/assets/78237731/f520e374-edd3-4c6c-88da-8637c4ee5d37)

Here are the mod I am using if you can't replicate this.
Torch
Forge Config API Port
fabricForceLowercase
No Resource Pack Warnings
Xaero's World Map
Xaero Zoomout
StatsSearch
Methane
Zoomify
Iris Shaders
Sodium
ThreadTweak
ModernFix
Lithium
ImmediatelyFast
FerriteCore
Exordium
Entity Culling
Concurrent Chunk Management Engine
YetAnotherConfigLib
TCDCommons API
Fabric Language Kotlin
Fabric API
Cloth Config API
Architectury API
Xaero's Minimap
Wider Stats Screen
Just Enough Items
Better Statistics Screen
AppleSkin
3D Skin Layers
WorldEdit
WorldEdit CUI
ViaFabricPlus
Perspektive
No Mining Cooldown
Carpet
Auth Me
Mod Menu
Inventory HUD+
MiniHUD
Litematica
Item Scroller
MaLiLib
Tweakeroo

**Comment by MCRcortex** [comment]
This should be fixed as of nvidium 0.2.1
