### ISSUE TITLE
Nether fog is inverted when nvidium is enabled

### ISSUE THREAD

**Issue by Colaskink** [MCRcortex/nvidium#111]
Minecraft version: 1.20.1
Nvidium version: 0.2.3-beta
Sodium version: 0.5.3
Mod loader: Quilt 0.22.0-beta.1

Whenever i enter the nether, all of the chunks in my vicinity have fog applied to them, as if they were far away from me.
Vice versa, the chunks far away from me are visible

With Nvidium:
![2023-12-07_16 33 09](https://github.com/MCRcortex/nvidium/assets/118903552/d0cb5e9a-6eec-4995-8b2d-fb4476154d85)

Without Nvidium:
![2023-12-07_16 33 37](https://github.com/MCRcortex/nvidium/assets/118903552/ef659bfb-3af9-4fc6-82c6-1b480b089043)

Log:
[latest.log](https://github.com/MCRcortex/nvidium/files/13602023/latest.log)

**Comment by nekohacker591** [comment]
well for now you should use the nofog mod as a softfix

**Comment by Colaskink** [comment]
I just tried [No Fog](https://modrinth.com/mod/no_fog), with all types of fog disabled, but it doesn't seem to do anything.

**Comment by ST-DDT** [comment]
Might be related:

- https://github.com/MCRcortex/nvidium/issues/131

(I also have better nether and no fog and I still have fog)

**Comment by ST-DDT** [comment]
I found a solution to the/my No fog issue:

Turning off bclib's `Nether Thick Fog`

![grafik](https://github.com/MCRcortex/nvidium/assets/1579362/fa41c949-2639-4d54-a1f1-c50944fd2e12)

**Comment by Colaskink** [comment]
Thank you! This fixed the problem for me
