### ISSUE TITLE
[Compatability request] Compatability with Chunks fade in

### ISSUE THREAD

**Issue by Colaskink** [MCRcortex/nvidium#112]
Right now, when Nvidium is enabled there are no chunk animations when they're being rendered.

**Comment by Kereswedhen** [comment]
Works fine for me

**Comment by GisusCryst** [comment]
I also had this issue on 1.20.1, and disabling Nvidium fixed the animations.

**Comment by SethBurkart123** [comment]
Also have the same issue, 1.20.4 - nvidium + chunks fade in

**Comment by KarmaMarazu** [comment]
Same as #56
