### ISSUE TITLE
[suggestion] disable mod when using non-nvidia gpu automatically.

### ISSUE THREAD

**Issue by Linksapprentice** [MCRcortex/nvidium#115]
This may already be a feature, but I think it would be helpful if the mod disabled itself whenever someone wasn’t using an nvidia gpu automatically, in the same way it deactivates with shaders. This would make it so you could use the mod in large modpacks without worrying about players exact setups. This may already be a feature, but I can’t check, as I have an nvidia gpu.

**Comment by MCRcortex** [comment]
This is already the case
