### ISSUE TITLE
[Compatability request] Compatability with Shimmer

### ISSUE THREAD

**Issue by mrvisert** [MCRcortex/nvidium#117]
Hello, is there any plans to support the Shimmer mod?(https://www.curseforge.com/minecraft/mc-mods/shimmer) Now, when the world starts, the game crashes
[crash-2023-12-16_12.04.28-client.txt](https://github.com/MCRcortex/nvidium/files/13691973/crash-2023-12-16_12.04.28-client.txt)

Version: 1.20.1
ModLoader: fabric 0.15.1

ModsList:
sodium-fabric-mc1.20.1-0.5.3
nvidium-0.2.4-beta
fabric-api-0.91.0+1.20.1
Shimmer-fabric-1.20.1-0.2.3

**Comment by MikiP98** [comment]
NVIDIUM doesn’t crash with Shimmer. It makes bloom always on, and coloured lights not working.
The crash you described seems like [shimmers #88](https://github.com/Low-Drag-MC/Shimmer/issues/88). Which is Sodium 5.3 incomapibylity with versions 0.2.0+ of Shimmer. Downgrade shimmer to 0.2.0 or downgrade Sodium and NVIDIUM.
