### ISSUE TITLE
Chunk rendering breaking

### ISSUE THREAD

**Issue by Duality4Y** [MCRcortex/nvidium#120]
unsure if related to any other issue but this is what happens to me:
I run the world with nvidium and often this works fine up until a point the "top layers" of chunks are not rendered in spots anymore
see pictures:
![2023-12-31_14 47 36](https://github.com/MCRcortex/nvidium/assets/1276401/a6190d96-04c1-4b7d-8655-0ba073be08cb)
after F3+A (reload chunks)
![2023-12-31_14 48 36](https://github.com/MCRcortex/nvidium/assets/1276401/b0e7b165-fc04-4a6c-8bfc-e1d45b619047)
to the left of the prior image.
![2023-12-31_14 48 48](https://github.com/MCRcortex/nvidium/assets/1276401/bff5495d-23c6-4fca-8fa6-c522a35ea314)

Logs:
https://api.paste.ee/p/wmNUy
[Minecraft_log_31_12_2023.txt](https://github.com/MCRcortex/nvidium/files/13801347/Minecraft_log_31_12_2023.txt)

Mods:
  [✔️] c2me-fabric-mc23w45a-0.2.0+alpha.11.28.jar
  [✔️] cloth-config-12.0.109-fabric.jar
  [❌] DistantHorizons-2.0.1-a-1.20.2.jar.disabled (disabled)
  [✔️] enhancedblockentities-0.9+1.20.2.jar
  [✔️] entityculling-fabric-1.6.2-mc1.20.1.jar
  [✔️] fabric-api-0.90.10+1.20.3.jar
  [✔️] ImmediatelyFast-1.2.7+1.20.2.jar
  [✔️] indium-1.0.27+mc1.20.1.jar
  [✔️] libjf-3.14.1.jar
  [✔️] lithium-fabric-mc1.20.2-0.12.0.jar
  [✔️] modernfix-fabric-5.8.2-beta.23+mc23w45a.464c.jar
  [✔️] moreculling-1.20.1-0.19.0.jar
  [✔️] nvidium-0.2.4-beta.jar
  [✔️] slyde-1.7.3.jar
  [✔️] sodium-fabric-mc23w44a-0.5.3+git.86b69d2.jar
  [✔️] threadtweak-fabric-1.20.2-0.1.1.jar
  [✔️] vmp-fabric-mc23w45a-0.2.0+beta.7.128-all.jar

hardware:
AMD Ryzen 7 5700G with Radeon Graphics
NVIDIA Corporation GA104 [GeForce RTX 3060 Ti] (rev a1)
Subsystem: Hewlett-Packard Company GA104 [GeForce RTX 3060 Ti]
Kernel driver in use: nvidia
Advanced Micro Devices, Inc. [AMD/ATI] Cezanne (rev c8)
DeviceName: OnBoard IGD
Subsystem: Hewlett-Packard Company Cezanne
OpenGL version string: 4.6.0 NVIDIA 470.223.02

32GB ddr4-3200 ram installed.
Java Arguments:
[-Xms512m, -Xmx25000m, -Duser.language=en]

had to kill java in this one because for some reason memory usage spiked beyond the specified 25000m assigned.

how to reproduce:
for me install simply optimized install nvidium
set any render distance beyond 64 Chunks (haven't seen it happen below this value)

similar issues?:
#107 
#105 
#64 
#78

**Comment by MCRcortex** [comment]
This issue is probably related to your vram filling up and nvidium automatically removing terrain that you havent seen for a while so that it can load more geometry, when this happens is your gpu memory full?
