### ISSUE TITLE
Weird Texture Glitch (1.20.1)

### ISSUE THREAD

**Issue by GisusCryst** [MCRcortex/nvidium#121]
![2024-01-02_20 44 13](https://github.com/MCRcortex/nvidium/assets/155504000/fd1d7eee-a1fa-4030-8310-92780ae1c80f)

idk what else to say about it. It just exists.

**Comment by GisusCryst** [comment]
the Nvidium version is 0.2.4-beta

**Comment by KingRocco21** [comment]
Cortex is aware of this and is working on a fix

**Comment by MCRcortex** [comment]
Patched as of 0.2.5
