### ISSUE TITLE
How to determine working state

### ISSUE THREAD

**Issue by steshi-chama** [MCRcortex/nvidium#13]
Hi,
As I see it, there is currently no way of knowing why the mod wouldn't work, right?
I've downloaded and installed the latest fabric mod loader and pasted the mod as well as sodium and the fabric api in the "mods" folder of my MC installation. Sodium seems to be working just fine and I also see the menu for nvidium, but no matter the options I choose, nothing changes for me. Not even using more vRAM, no more CPU usage, nothing.
How can I determine why it's not doing anything at all?

**Comment by Funtimes909** [comment]
Upload your log file and most importantly tell us what graphics card you have

**Comment by steshi-chama** [comment]
By log I'm going to assume you're talking about the "latest-log" file.
Also, I'm rocking a Gigabyte Nvidia RTX 2080.

[latest.log](https://github.com/MCRcortex/nvidium/files/11365186/latest.log)

**Comment by MCRcortex** [comment]
hmm what do you mean nothing changes? if you disable chunk unloading and fly around do chunks still unload?
