### ISSUE TITLE
OpenGL debug message: id=1281.  Invalid size and/or offsets.'

### ISSUE THREAD

**Issue by GRocket-GamingGalaxy** [MCRcortex/nvidium#130]
Game freezes the crashes, Nvidium 0.2.5-beta, Nvidia GTX 1650S.

#58 Same OpenGL error

LOG:
https://mclo.gs/140bIVC

`[07:59:49] [Render thread/INFO]:
 Loaded 714 advancements
[07:59:54] [Render thread/INFO]:
 Loaded 714 advancements
[07:59:55] [Render thread/INFO]:
 Loaded 717 advancements
[08:00:18] [Render thread/INFO]:
 [CHAT] {MINECRAFT_USERNAME} fell from a high place
[08:00:41] [Render thread/INFO]:
 Stopping worker threads
[08:00:41] [Render thread/INFO]:
 Started 6 worker threads
[08:00:42] [Render thread/INFO]:
 Stopping worker threads
[08:00:42] [Render thread/INFO]:
 Started 6 worker threads
[08:02:24] [Render thread/INFO]:
 Stopping worker threads
[08:02:24] [Render thread/INFO]:
 Started 6 worker threads
[08:02:24] [Render thread/INFO]:
 Stopping worker threads
[08:02:24] [Render thread/INFO]:
 Started 6 worker threads
[08:03:43] [Render thread/INFO]:
 [CHAT] The123123123 left the game
[08:04:29] [Render thread/INFO]:
 Loaded 717 advancements
[08:05:08] [Render thread/INFO]:
 Loaded 717 advancements
[08:05:25] [Render thread/WARN]:
 Unable to play empty soundEvent: minecraft:entity.tropical_fish.ambient
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:28] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:29] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:31] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:32] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:32] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:32] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:32] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:32] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:33] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:36] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:05:36] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:06:03] [Render thread/ERROR]:
 Signature is missing from Property textures
[08:06:34] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'
[08:06:44] [Render thread/INFO]:
 OpenGL debug message: id=1281, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_VALUE error generated. Invalid size and/or offsets.'`

**Comment by Gamer95875** [comment]
I would like to add that this occurs for me too, with Nvidium 0.2.9-beta, on Minecraft 1.21, Prism Flatpak, using an RTX 3060. (this bug has been occurring for the past few days, with the duration until the game freezes decreasing, to the point where the game is freezing 3 minutes after joining a world, with the game having a few lag spikes prior to freezing)

**Comment by ferriarnus** [comment]
What other mods are you using? As this can be caused by a mod using a different stencil depth format iirc. *For example on forge, mods can enable the depth stencil and it will take a different format, IE is an example of such a mod.*

**Comment by MCRcortex** [comment]
If this is still an issue in the next release please reopen the issue
