### ISSUE TITLE
Crazy Input Lag at High Render Distances

### ISSUE THREAD

**Issue by TheCrafter8000** [MCRcortex/nvidium#132]
I havent tested it much but it seems at range of like 20 - 32 the input lag becomes insane for a lil bit, i assume its becuase its loading a lot but it becomes almost unplayable. Im running a 14900K with a 3080

**Comment by TheCrafter8000** [comment]
I would like to add on that i am using the power saving plan in control panel which underclocks my cpu and maybe my gpu i think. The reason i am doing this is i have to get a new power supply and without using power saving mode on minecraft my pc shuts off. That could be a factor but it wouldnt make much sense why i would be getting so much lag

**Comment by KingRocco21** [comment]
What fps are you getting when this happens?

**Comment by TheCrafter8000** [comment]
I dont get any fps drops

**Comment by ayushthoren** [comment]
Try pressing f3+2 to open the frame/tick time monitors, is your tps really low? That can delay when actions register in the world.

**Comment by TheCrafter8000** [comment]
its not tps i wouldnt think, cause pressing F5 to change my perspective is also delayed, aswell as my zoom button sometimes, and things like moving my mouse and pressing wasd. I was also playing on a server.

**Comment by TheCrafter8000** [comment]
It seems to only be when its loading chunks, because after a bit everything smooths out and its fine.

**Comment by KingRocco21** [comment]
Even if you’re not getting fps drops, it would help to know your average fps when this happens

**Comment by TheCrafter8000** [comment]
ok, ill have to check it when i play again, i normally have v-sync on

**Comment by SetOfAllSets** [comment]
I'm playing with a 2070 max-q refresh mobile and I get the same issue when I go from 256 to 512 render distance

**Comment by KingRocco21** [comment]
Now that I think about it, I’ve never tried a render distance past 256. I’ll try 512 soon with my 4070 and see what happens.

**Comment by TheCrafter8000** [comment]
how do you get that high lmao, im having this issue at 32 chunks

**Comment by TheCrafter8000** [comment]
but to comment on my average fps, i do remember that im sure its 165 solid all the time with v-sync adaptive on so i assume its getting way more than that

**Comment by KingRocco21** [comment]
Nothing happened for me at 512 render distance, maybe try turning vsync off

**Comment by TheCrafter8000** [comment]
I have and the issue still persists

**Comment by KingRocco21** [comment]
Are you sure this isn’t an issue with your hardware? Does this happen in other games?

**Comment by SetOfAllSets** [comment]
> Are you sure this isn’t an issue with your hardware? Does this happen in other games?

I've yet to experience this in another game. I am running a 2070 max-q refresh mobile with the proprietary drivers on Debian Linux.

**Comment by KingRocco21** [comment]
I have no idea sry. Maybe try fiddling with mods or settings

**Comment by 8n76** [comment]
hey uh, this issue just started happening to me. i play on a singleplayer world with 88 chunk render distance, with a rtx 2060 super and a ryzen 7 2700 and its been fine for ab 1.5 weeks until now, and im getting (like every 15 seconds) crazy input lag  (talking about 1-2 second delay). my mods are as following: appleskin, bobby, borderless mining, carpet and carpet fixes, cloth config, kotlin, forge cfg api port, kypton, lazydfu, memoryleakfix, modmenu, more culling (and extra), nvidium, reeses sodium options, REI, sodium extra, sodium, xaeros minimap, zoomify, and whatever API's those mods require.

**Comment by 8n76** [comment]
ok, i seem to have fixed it simply by restarting my computer. i will come back if the issue persists
