### ISSUE TITLE
Transparency bug

### ISSUE THREAD

**Issue by SetOfAllSets** [MCRcortex/nvidium#133]
While glass transparency in front of water is fixed, the outline a block has when hovered over still lets you see through the water as if it weren't there.

**Comment by Ivanmatthew** [comment]
> While glass transparency in front of water is fixed, the outline a block has when hovered over still lets you see through the water as if it weren't there.

Do you have a picture of this?

**Comment by SetOfAllSets** [comment]
![2024-01-17_15 15 46](https://github.com/MCRcortex/nvidium/assets/98566029/c4b5605c-2dff-4e87-98c5-2f5ab9e7e866)
It is fairly visible over the sand

**Comment by Ivanmatthew** [comment]
> ![2024-01-17_15 15 46](https://private-user-images.githubusercontent.com/98566029/297545993-c4b5605c-2dff-4e87-98c5-2f5ab9e7e866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjM1NjksIm5iZiI6MTcwNTc2MzI2OSwicGF0aCI6Ii85ODU2NjAyOS8yOTc1NDU5OTMtYzRiNTYwNWMtMmRmZi00ZTg3LTk4YzUtMmY1YWI5ZTdlODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE1MDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTE3OWE3OTBhM2VmMzQ2ZGQ3NDkzOTI0ZjE5ZjEwNWFiYTVmYzNlYjdkNzA2YzMxZmM4ZjA4N2IwZTI3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cb4KXCqptukmnoxZ0HusDCfUyhwqFzj5NwiD1yoCFUg) It is fairly visible over the sand

Related issue:
https://github.com/CaffeineMC/sodium-fabric/issues/1326

As it is supposedly a Vanilla issue, I don't think any attention will be spent on it.

**Comment by SetOfAllSets** [comment]
> > ![2024-01-17_15 15 46](https://private-user-images.githubusercontent.com/98566029/297545993-c4b5605c-2dff-4e87-98c5-2f5ab9e7e866.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NjM1NjksIm5iZiI6MTcwNTc2MzI2OSwicGF0aCI6Ii85ODU2NjAyOS8yOTc1NDU5OTMtYzRiNTYwNWMtMmRmZi00ZTg3LTk4YzUtMmY1YWI5ZTdlODY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE1MDc0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTE3OWE3OTBhM2VmMzQ2ZGQ3NDkzOTI0ZjE5ZjEwNWFiYTVmYzNlYjdkNzA2YzMxZmM4ZjA4N2IwZTI3MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cb4KXCqptukmnoxZ0HusDCfUyhwqFzj5NwiD1yoCFUg) It is fairly visible over the sand
> 
> Related issue:
> https://github.com/CaffeineMC/sodium-fabric/issues/1326
> 
> As it is supposedly a Vanilla issue, I don't think any attention will be spent on it.

Nvidium fixes the water and glass transparency bug with sodium, so I'm not sure
