### ISSUE TITLE
Hardware Question

### ISSUE THREAD

**Issue by catluvr86** [MCRcortex/nvidium#134]
Found this on YouTube, works awesome! 

I was wondering though, why does this only work on NVidia GPUS, and more specifically the 1600 series? I am pursuing a degree in cybersecurity and am trying to get a bit more into chip architecture but am still very beginner haha. What generally makes this not work on other hardware technologies?

Thank you! Sorry for adding an issue, can't figure out how else to ask.

**Comment by KingRocco21** [comment]
Cortex mentioned something about requiring Turing architecture gpus, so NVIDIA probably only supports mesh shaders on that architecture and above
