### ISSUE TITLE
NVidia proprietary driver on the Linux kernel

### ISSUE THREAD

**Issue by Pdam67** [MCRcortex/nvidium#137]
Does this mod work with the NVidia proprietary driver on the Linux kernel?

And how would I know if it doesn't work?

**Comment by KingRocco21** [comment]
Try it and see what happens, it will probably work

**Comment by Pdam67** [comment]
Well the problem is it doesn't work, it could be a problem with the mod (doubt it), it could be a problem with the fact that Minecraft is running in a flatpak and it could also be that NVidia just never implemented the mesh shaders into the proprietary drivers which are know to be an after though. I just wanted to see if the mod developer has support for Linux.

**Comment by SpaaceManBob** [comment]
Does the F3 menu show "Using nvidium renderer" on the right side?

I thought it wasn't working in spite of showing that, but after comparing nvidium off and on more closely it appears to be working, just not nearly as well as on Windows. The difference vs only Sodium on Windows is massive, on Linux it's much less.

Seeing as I'm not using Flatpak, I'd guess it's the proprietary Nvidia drivers being trash on Linux. It works, just not as well as on Windows with the nice shiny drivers.

**Comment by Pdam67** [comment]
Perhaps because I am using a Flatkpak, Minecraft is using a pre-installed OpenGL that comes bundled with the launcher i'm using, Prismlauncher.

I'm going to try and install the AUR instead.

**Comment by SpaaceManBob** [comment]
Yea, if yours indeed doesn't work at all, it may well be Flatpak introducing the issue. 

For what it's worth, I've got Minecraft running from the AUR, and nvidium works, so maybe that'll fix it for you as well.

**Comment by Nextross** [comment]
@Pdam67 Have you resolved your issue? I also run Minecraft on Linux (Pop OS) and when I tried Nvidium, it didn't work. Also using Prism Launcher (installed through AppImage if it matters). It just (probably) disables itself on launch. Launcher console doesn't show any errors

**Comment by KarmaMarazu** [comment]
> @Pdam67 Have you resolved your issue? I also run Minecraft on Linux (Pop OS) and when I tried Nvidium, it didn't work. Also using Prism Launcher (installed through AppImage if it matters). It just (probably) disables itself on launch. Launcher console doesn't show any errors

i run pop os aswell and it does work for me thi i have the flatpack version of prism

**Comment by Pdam67** [comment]
I had never resolved the issue, I did not mean to resolve the issue as complete.

I had tried with and without installing via the system package manager as well as different distributions and different Nvidia proprietary drivers and I couldn't get it to work.

The worst part is, no console logs or an indication on whether it is working or not.

If you know more about Linux than I do then you can try finding a fix.

**Comment by Pdam67** [comment]
> > @Pdam67 Have you resolved your issue? I also run Minecraft on Linux (Pop OS) and when I tried Nvidium, it didn't work. Also using Prism Launcher (installed through AppImage if it matters). It just (probably) disables itself on launch. Launcher console doesn't show any errors
> 
> i run pop os aswell and it does work for me thi i have the flatpack version of prism

This issue may be related to some other factor that I do not know of then.

**Comment by MrDuartePT** [comment]
I know this is closed as not planed but just to give some feadback.
The mod work on linux just fine on the lastest nvidia driver (555 on time of writting).

The nvidia driver on linux also support `mesh_shaders`:
```bash
user@Gentoo ~ $ glxinfo | grep GL_NV_mes
    GL_NV_memory_attachment, GL_NV_memory_object_sparse, GL_NV_mesh_shader,
    GL_NV_memory_attachment, GL_NV_memory_object_sparse, GL_NV_mesh_shader,
    GL_NV_memory_attachment, GL_NV_memory_object_sparse, GL_NV_mesh_shader,
 ```
 
 Bellow is also a image of the gaming showing nvidium render:

![image](https://github.com/MCRcortex/nvidium/assets/68701049/41d754d7-2a24-40bb-ade8-96c478110a7e)
