### ISSUE TITLE
Vulkan version

### ISSUE THREAD

**Issue by Martinligabue** [MCRcortex/nvidium#138]
After reading https://github.com/MCRcortex/nvidium/issues/41 and https://github.com/MCRcortex/nvidium/issues/52, I see that Minecraft's default use of OpenGL is the main issue.
However, I have tested https://github.com/xCollateral/VulkanMod and it worked perfectly. By combining this mod with the other one, we could potentially solve the problem. Moreover, creating a Vulkan version of the mod would increase its compatibility, enabling it to support Intel and AMD systems in addition to Nvidia.
Do you think there's a chance of it working?

**Comment by ayushthoren** [comment]
But this mod uses OpenGL features to function... how would that be transferred over to Vulkan?

**Comment by Martinligabue** [comment]
that's what I'm asking, is it feasible?

**Comment by KingRocco21** [comment]
Ask in the discord, cortex is more active there

**Comment by Ivanmatthew** [comment]
> But this mod uses OpenGL features to function... how would that be transferred over to Vulkan?

I have read that Vulkan also has support for mesh shading, which is the technology utilized by Nvidium with OpenGL.
It is most definitely possible to make a Vulkan port.

[https://www.khronos.org/blog/mesh-shading-for-vulkan](https://www.khronos.org/blog/mesh-shading-for-vulkan)
[https://developer.nvidia.com/blog/using-mesh-shaders-for-professional-graphics/](https://developer.nvidia.com/blog/using-mesh-shaders-for-professional-graphics/)

**Comment by Eeveelution** [comment]
making it available for vulkan would also solve the nvidia only issue, as VK_EXT_mesh_shader is available on most modern GPUs

**Comment by ferriarnus** [comment]
Yes, but nvidium also depends on sodium. So for a vulkan version, someone also needs to rewrite sodium to use vulkan. Or rewrite vulkanmod to use a sodium-like pipeline, neither I see happening soon due to the amount of work this would be with little payoff.

**Comment by Splarkszter** [comment]
> making it available for vulkan would also solve the nvidia only issue, as VK_EXT_mesh_shader is available on most modern GPUs

Only RDNA2 and up (6000 series and up) have hardware support for Mesh Shaders.

But yeah, it would be pretty cool since AMD is the current price/performance king.

**Comment by Andarwinux** [comment]
`EXT_mesh_shader` does not performance as well as `NV_mesh_shader` , in addition, the mesh shader may have performance issues on RDNA2.

**Comment by Esensats** [comment]
> Yes, but nvidium also depends on sodium. So for a vulkan version, someone also needs to rewrite sodium to use vulkan. Or rewrite vulkanmod to use a sodium-like pipeline, neither I see happening soon due to the amount of work this would be with little payoff.

Does [VulkanMod](https://github.com/xCollateral/VulkanMod) have a "sodium-like pipeline"? I mean, is it possible to, let's say, fork it and make it utilize mesh shaders to achieve results similar to Nvidium? How feasible is it?

**Comment by beedell-roke** [comment]
[`GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4`](https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4#issue-2308252009) relates.

**Comment by qweeren** [comment]
what is the state of vulkan support?
since sodium has a vulkan renderer now
