### ISSUE TITLE
`More memory than limit allows was attempted to be allocated` when rendering large number of blocks with high polygon count

### ISSUE THREAD

**Issue by Malfrador** [MCRcortex/nvidium#14]
Rendering a large amount of blocks with a high polygon count (for example dragon eggs, bells) causes a instant client crash with a `
java.lang.IllegalStateException: More memory than limit allows was attempted to be allocated` error. Without Nvidium the client does not crash, it just performs worse (as expected)

1. Use WorldEdit or similar to set a large amount of dragon eggs (e.g. 400k)
2. Client crashes with the attached crash report
3. Uninstall nvidium -> only about 150 FPS, but no client crash.

[crash-2023-05-01_18.32.36-client.txt](https://github.com/MCRcortex/nvidium/files/11366646/crash-2023-05-01_18.32.36-client.txt)

**Comment by MCRcortex** [comment]
this should be fixed as of 0.2.4-beta
