### ISSUE TITLE
Why did you go for Mesh-Shaders instead of Compute-Shaders?

### ISSUE THREAD

**Issue by mubin-thinks** [MCRcortex/nvidium#142]
As far as I know about OpenGL is you can use the Compute-Shader to parallelize CPU instruction in the GPU. So, why not use that for chunk-loading. Wouldn't it give the same level of performance? If it can be pulled off then nvidium will support both AMD and Nvidia GPUs. (Then the name might have to change)

Another question I have, Can I use C++ for creating Minecraft mods?
Thanks.

**Comment by KingRocco21** [comment]
Cortex has said in the past that they use mesh shaders for rasterized occlusion culling. As for C++, no, because mod loaders use Java.

**Comment by KingRocco21** [comment]
Please disregard what I said about C++! I just heard that you can code in other languages using JNI. Ask cortex in the discord if you need more information, that’s all I know.

**Comment by mubin-thinks** [comment]
Thanks, it would be great if it works.
