### ISSUE TITLE
chunk culling while i'm a few blocks near it.

### ISSUE THREAD

**Issue by voshn** [MCRcortex/nvidium#143]
this is annoying
![Screenshot 2024-01-28 120333](https://github.com/MCRcortex/nvidium/assets/157944750/556bfcb0-ef4b-4094-b2da-8728ba45eba5)

**Comment by endercatone** [comment]
I'm having the same problem

**Comment by MCRcortex** [comment]
can you send an f3 screen and world seed

**Comment by voshn** [comment]
ok

**Comment by voshn** [comment]
fyi i am using the modrinth launcher with the mods below:
Axes are weapons
Bobby
Cardinal Components API
Cloth Config API
Collective
Easy Elytra Takeoff
Entity Culling
Fabric API
Mod Menu
Nvidium(your mod)
Sodium
Traveller's Backpack
Worldedit
Xaero's Minimap
Xaero's Worldmap

**Comment by voshn** [comment]
![Screenshot 2024-02-03 190148](https://github.com/MCRcortex/nvidium/assets/157944750/520b8e73-f3d5-405c-90a8-c187b713d913)

right now its back to normal

**Comment by voshn** [comment]
Seed: -460463846880087512
and the world generation has differed compared to the original world due to mods as I have seen in Chunkbase.

**Comment by KarmaMarazu** [comment]
Ran out of vram
