### ISSUE TITLE
Update for Sodium 0.5.6

### ISSUE THREAD

**Issue by Lucario4LyfeYT** [MCRcortex/nvidium#144]
https://modrinth.com/mod/sodium/version/mc1.20.3-0.5.6

**Comment by dopadream** [comment]
wow what a waste of an issue, like yeah im sure they know dude just be patient and maybe close this so they can keep actual issues with the mod organized

**Comment by dopadream** [comment]
someone mark this shit as invalid

**Comment by ghost** [comment]
This is a valid issue.

**Comment by KingRocco21** [comment]
Please calm down and be respectful, this issue is just here to note that nvidium needs an update to support the new version.

**Comment by TheTrashCrafter** [comment]
Or update to 0.5.7, they just released another update.

**Comment by Lucario4LyfeYT** [comment]
I'm a very patient person. I was just making the note that sodium has updated, and since this mod requires sodium to run, and use properly, I thought it would be useful to tell the creator of this amazing mod that the mod he's essentially developing for, has been updated. Now, I understand that the mod creator probably keeps tabs on sodium updates, but at the same time, who knows?

-Best wishes
           Lucario4LyfeYT

**Comment by Felix14-v2** [comment]
Done, you can close the issue
https://modrinth.com/mod/nvidium/version/0.2.6-beta
Not featured, but published
