### ISSUE TITLE
Port to earlier versions

### ISSUE THREAD

**Issue by metaltiger775** [MCRcortex/nvidium#145]
Will there ever be a port oof Nvidium to earlier versions of Minecraft such as 1.18.2, 1.16.5 or others?

**Comment by KarmaMarazu** [comment]
Cortex has said only if sodium 0.5.3 or 0.5.5 get ported to that version then yes else probs no

**Comment by ghost** [comment]
> Cortex has said only if sodium 0.5.3 or 0.5.5 get ported to that version then yes else probs no

Sodium will most likely not be porting to earlier versions.

**Comment by KarmaMarazu** [comment]
> Sodium will most likely not be porting to earlier versions.

there for the answer is simple then it wont be ported to older versions
