### ISSUE TITLE
Error with Sodium 0.5.8

### ISSUE THREAD

**Issue by GrimPlayzs** [MCRcortex/nvidium#147]
Upon loading into a world, an error occurs which prevents the loading of chunks. Disabling Nvidium makes the chunks visible again.

```
[Cull thread/INFO]: [STDERR]: Error doing traversal
[Cull thread/INFO]: [STDERR]: java.lang.NoSuchMethodError: 'void me.jellysquid.mods.sodium.client.render.chunk.occlusion.OcclusionCuller.findVisible(java.util.function.Consumer, me.jellysquid.mods.sodium.client.render.viewport.Viewport, float, boolean, int)'
[Cull thread/INFO]: [STDERR]: at me.cortex.nvidium.managers.AsyncOcclusionTracker.run(AsyncOcclusionTracker.java:97)
[Cull thread/INFO]: [STDERR]: at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by CelDaemon** [comment]
That's correct, nvidium doesn't currently support sodium 0.5.8, and shouldn't even be able to pass the dependency check stage of fabric (???)
I've attempted to port the mod to sodium 0.5.8 myself, but as cortex is already aware, a major change in the world format occurred between 0.5.5-0.5.6 and it might require some time to rewrite.

EDIT: New version now has support for sodium 0.5.7-0.5.8
