### ISSUE TITLE
Cursor never focuses when fastload is installed

### ISSUE THREAD

**Issue by Cartrigger** [MCRcortex/nvidium#148]
Fastload (a very nice worldgen optimization mod) when loaded with Nvidium and make a Singleplayer world, the cursor never focuses and thus you cannot play the game.

Windows 11 Pro
MC 1.20.1

**Comment by RedCrafter07** [comment]
Same issue here

**Comment by Felix14-v2** [comment]
This is a known issue of FastLoad. Just don't use it. If you want faster world load, use ModernFix instead
