### ISSUE TITLE
Pistons crash the game

### ISSUE THREAD

**Issue by nervich** [MCRcortex/nvidium#149]
When pushing a piston, the game freezes (before the extended piston head even appears) and then crashes.

The game crashed whilst rendering block entity
Error: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.Renderer.meshBuilder()" because the return value of "net.fabricmc.fabric.api.renderer.v1.RendererAccess.getRenderer()" is null
[crash-2024-02-04_16.00.47-client.txt]

Dump:
(https://github.com/MCRcortex/nvidium/files/14157272/crash-2024-02-04_16.00.47-client.txt)

**Comment by ayushthoren** [comment]
Do you have indium installed? I've had issues in the past with moving block entities like sand and pistons crashing the game in any situation (with or without nvidium), and it was just because I didn't have that lol.

**Comment by nervich** [comment]
For anyone wondering where to find indium for sodium 0.5.8 and nvidium 0.2.6: You have to use an older version. Current highest versions compatable:
Sodium 0.5.3
Nvidium 0.2.5
Indium 1.0.27

Thank you gargondoid
