### ISSUE TITLE
The mod doesn't work

### ISSUE THREAD

**Issue by YaprostoDed** [MCRcortex/nvidium#15]
I installed the sodium and nvidium on a clean build. But the game does not change the drawing chunks and fps no more.
RTX 3050
I3-8350K

**Comment by MCRcortex** [comment]
Can you send log? is the config tab visible at all?

**Comment by YaprostoDed** [comment]
> Can you send log? is the config tab visible at all?

I don't know how to enable debugging (unless you mean in-game). And there is a tab with the mod and everything switches, but nothing changes

**Comment by Timolino456** [comment]
You need to send the file called "latest.log" (or just "latest" if you don't have file extensions being shown enabled), it's located in .minecraft/logs. Make sure you opened the instance where you have nvidium installed before sending, as the log gets overwritten every time a new Minecraft session is started.

**Comment by MCRcortex** [comment]
Stale, if you have this issue again please reply or create a new issue
