### ISSUE TITLE
Fog issue on Region Keep Distances greater than 32

### ISSUE THREAD

**Issue by BenPerkins-HunterOrbit** [MCRcortex/nvidium#151]
Likely a known issue with how minecraft/Fabric works, but you can see the nice fog blending in with the sky effect on 32 Region Keep Distance.
![image](https://github.com/MCRcortex/nvidium/assets/99301434/4b9a7e4c-f76b-43f9-821f-3898c7d6dcae)

But then on greater than 32 (80 in this example), you can see how harsh the transition is between fog and sky. 
![image](https://github.com/MCRcortex/nvidium/assets/99301434/dab8d250-78c9-4e2f-b3df-2ef8bb95a2fd)

Weirdly, with nvidium disabled, using C2ME to increase render distance to 80 chunks, while in the menu the fog renders properly in the background as seen below, but it seems limited to 32 chunks actually rendered.
![image](https://github.com/MCRcortex/nvidium/assets/99301434/95eaefb1-42c5-4a1e-b9f6-cf48f86f6aec)

But then when unpausing the game it re-renders the full 80 and breaks the fog/sky again.
![image](https://github.com/MCRcortex/nvidium/assets/99301434/12bd7119-4702-4c62-b1d1-0e4ed70116ea)

Just confirming, this effect DOES happen without C2ME installed. Nvidium itself breaks the fog/sky effect at higher than 32 region keep distance while only rendering 32 chunks. This makes me think there's an issue with how nvidium/c2me similarly integrate with the fabric API? Or a limitation of the game itself? Open to ideas from people smarter than myself. Thanks :)

**Comment by KarmaMarazu** [comment]
#160
