### ISSUE TITLE
falling blocks cause minecraft to crash

### ISSUE THREAD

**Issue by deadfry42** [MCRcortex/nvidium#154]
details:
os : arch linux 6.7.4-arch1-1
server : multiplayer (play.kiwismp.fun), also occurs on singleplayer
minecraft version: 1.20.1 (fabric)
mod version : 0.2.6-beta
mod settings: default (no changes)

see the video for a demonstration:
https://github.com/MCRcortex/nvidium/assets/75206733/12a27b4c-dc24-496e-8cf1-665502bcaf06
github doesnt want to embed - oh well

mining a block below another block that can fall causes minecraft to crash, presumably nvidium cannot render falling blocks.

lmk if im doing something wrong lol, this is my first issue on this repo

**Comment by KarmaMarazu** [comment]
Sodium issue add indium

**Comment by deadfry42** [comment]
thank you lol
