### ISSUE TITLE
Incompatible with Sodium versions 5.6 and above

### ISSUE THREAD

**Issue by StrongSand94191** [MCRcortex/nvidium#157]
https://github.com/CaffeineMC/sodium-fabric/releases

**Comment by ayushthoren** [comment]
Have you updated the mod recently? The latest version supposedly added support for sodium 5.7 and 5.8...

**Comment by StrongSand94191** [comment]
> Have you updated the mod recently? The latest version supposedly added support for sodium 5.7 and 5.8...

Sorry, Prism Launcher just didn't detect the update from Modrinth for some reason. Thanks!
