### ISSUE TITLE
Please add AMD support with ZLUDA

### ISSUE THREAD

**Issue by Xanderman27** [MCRcortex/nvidium#161]
https://github.com/vosen/ZLUDA?tab=readme-ov-file

**Comment by 0-x-2-2** [comment]
This isn’t relevant

**Comment by asumagic** [comment]
ZLUDA implements CUDA over ROCm, which is unrelated to the set of OpenGL extensions that nvidium requires.

**Comment by bobcao3** [comment]
Hey I'm sorry to say, CUDA is not what this mod is based upon. If AMD decides to add these features to their OpenGL drivers then sure. Before that, nah

**Comment by AnnoyedDev** [comment]
Actually mesh shader is supported by AMD driver but only on the vulkan backend

**Comment by BoyBaykiller** [comment]
AMD has recently said this about their OpenGL Mesh Shader support (which is what nvidium uses): 
> The OpenGL team has replied that they have plan to support mesh shader for AMD OpenGL driver in the future.

So there is hope. https://community.amd.com/t5/opengl-vulkan/is-mesh-shader-support-planned-for-opengl/m-p/649970/highlight/true#M5068. 

The people who want AMD Mesh shader support might want to get active in that thread.

**Comment by FluffyPuppyKasey** [comment]
> https://github.com/vosen/ZLUDA?tab=readme-ov-file

ZLUDA is for running CUDA workloads on AMD/Intel GPUs. Nvidium does not use CUDA. Therefore, this is irrelevant.

**Comment by ImBehinYa** [comment]
I opened an issue in AMD's new driver forum on GitHub and already received a response. They are aiming for the end of the year. Maybe you should comment or react so they see that this matters to us.

https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4

**Comment by asumagic** [comment]
> I opened an issue in AMD's new driver forum on GitHub and already received a response. They are aiming for the end of the year. Maybe you should comment or react so they see that this matters to us.
> 
> [GPUOpen-Drivers/AMD-Gfx-Drivers#4](https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4)

I would recommend against this, mentioning it once like you did is fine since they asked for usecases but flooding a thread with the same request is frowned upon.
