### ISSUE TITLE
NullPointerException when toggling shaders

### ISSUE THREAD

**Issue by nathansCodes** [MCRcortex/nvidium#165]
I know Nvidium is not compatible with shaders, but I still do it just for fun sometimes.  I can normally do it 3-7 times in a row, but after toggling a couple of times, the game crashes. This seems to be because of a NullPointerException in Nvidium's code. 

I'm on [Nobara Linux](https://nobaraproject.org) (a gaming-focused Fedora fork) with a GTX 1650 / Max-Q with the 535.154.05 driver.
I can confirm this happens on both X11 and Wayland.

Crash report:
[crash-2024-02-24_20.44.48-client.txt](https://github.com/MCRcortex/nvidium/files/14394298/crash-2024-02-24_20.44.48-client.txt)

**Comment by MrCatlio** [comment]
try to update your drivers since you are on a out of date version and could be causing the issue if not then try disabling mods to see what mods causes it to crash

**Comment by nathansCodes** [comment]
I updated them to 550.54.14 and it still happens

**Comment by MCRcortex** [comment]
I believe this is a sodium issue, if this is still occurring please reopen the issue
