### ISSUE TITLE
[Suggestion/Request] Port this mod to the Forge (Rubidium/ Embeddium)

### ISSUE THREAD

**Issue by mmnvb** [MCRcortex/nvidium#166]
I thought it would be great to have the nvidium on forge clients as well. Since we already have a forks of Sodium for forge such as Rubidium or Embeddium

**Comment by Delfite** [comment]
This would be amazing to have, especially for large modpacks where you need to render tons of terrain just to get your whole Create factory into view. I'd also like for this mod to be on Curseforge for ease of installation and allow it's use in CF modpacks as a result.

**Comment by Atopik2** [comment]
Works fine with Sinytra Connector create contraptions go invisible tho

**Comment by Tapacywka** [comment]
https://github.com/ferriarnus/acedium
NVidium fork for NeoForge & Embeddium

**Comment by viziy** [comment]
What about normal Forge?

**Comment by zm-cttae** [comment]
Forge is dead. Long live Neoforge.
