### ISSUE TITLE
Invisible blocks with higher render distances

### ISSUE THREAD

**Issue by Ardelle7** [MCRcortex/nvidium#167]
This issue started happening randomly as I was exploring the ocean, and could only be fixed by disabling Nvidium. I tried disabling some culling mods, but it didn't help. This doesn't seem to happen on render distances <25 for the most part. All of my mods are updated to their latest version for 1.20.4 through Prism Launcher.

The picture below was taken with 43 render distance and 32 simulation distance.

![2024-03-01_13 39 51](https://github.com/MCRcortex/nvidium/assets/33297760/a0a647db-6ce0-48c7-9718-4a959b0f78f5)

Full mod list:
AppleSkin
BetterF3
Boosted Brightness
Cloth Config v13
Concurrent Chunk Management Engine
Continuity
Eating Animation
EntityCulling
essential-container
Fabric API
Fabric Language Kotlin
FerriteCore
Forge Config API Port
Freecam
Iceberg
ImmediatelyFast
Indium
Inventory Profiles Next
Krypton
LazyDFU
Legendary Tooltips
libIPN
Lithium
Logical Zoom
Make Bubbles Pop Mod
MaLiLib
Memory Leak Fix
MiniHUD
Mod Menu
More Culling
Nvidium
Perfect Accuracy
Prism
Shulker Box Tooltip
Sodium
Sodium Extra
Starlight
Trample Stopper
Trenzalore
Visuality
Vivecraft (flatscreen mode)
Xaero's Minimap
YetAnotherConfigLib

**Comment by JosDUisterhout** [comment]
I had the same issue until I unchecked the automatic memory limit and set the max gpu memory to my gpu's amount of vram.
