### ISSUE TITLE
The mod works great but the 'extra render distance' doesn't.

### ISSUE THREAD

**Issue by aiyafps** [MCRcortex/nvidium#17]
Mod works great, 'disable chunk unload' works great, but the 'extra render distance' doesn't seem to work for me at all. I've updated to the most recent version too.

**Comment by MCRcortex** [comment]
Ah yea, my apologies for that, im very bad at explaining things, extra render distance basically allows you to explore more chunks, it doesnt increase render distance directly, it just allows you to explore more chunks before the region counter fills up, in the future i plan to fix this properly so it loads in the extra render distance, just an unfortunate way of me explaining things

**Comment by aiyafps** [comment]
Ah okay I understand, thank you for the reply! It's great you're working on it. Regardless though, thank you for this truly revolutionary mod :)

**Comment by Pheryos** [comment]
absolute legend keep doing what your doing i hope this mod gets recognition it does deserve it and alot
so i have question
is the mod done and only has bugs or
the mod is unfinished with bugs?

**Comment by Owehttamy** [comment]
> absolute legend keep doing what your doing i hope this mod gets recognition it does deserve it and alot so i have question is the mod done and only has bugs or the mod is unfinished with bugs?

@Pheryos It's currently in alpha, which is an early testing phase. It was just released exactly three weeks ago, so it still needs a lot of time. It is functional enough to be used but is unpolished and often lacks many of the features that will be included in the final version, as well as usually being riddled with all sorts of bugs. So the mod is still far from completion and is bound to have many bugs.

**Comment by MCRcortex** [comment]
Removed the mislleading slider
