### ISSUE TITLE
 [Request] nVidium compatible with shaders

### ISSUE THREAD

**Issue by DandaCze** [MCRcortex/nvidium#170]
Hello
I've been using nVidium and i'm getting double fps so i tried use shaders but every time i tried to use any shaders nVidium disables itself no matter what i do. For full transparency im using nVidium with forge (by [this guide](https://www.reddit.com/r/feedthebeast/comments/17n9cfv/nvidium_forge_version/)) and with oculus.

btw if you're reading this i just want to say that im huge fan of this mod please keep it up

**Comment by rowinadrian1207** [comment]
It's not compatible with shaders

**Comment by DandaCze** [comment]
That's exacly my request, make it compatible with shaders.

**Comment by KarmaMarazu** [comment]
![Screenshot_20240303_091127](https://github.com/MCRcortex/nvidium/assets/98053409/a950d95e-97ba-40c5-9526-fbd94f1af17f)
No probably not gonna happen

**Comment by Riyuukii** [comment]
maybe posting the same request on IrisShader's Github can help? just in case if Iris Developer have an interest for adding this support, just like what Iris and Distant Horizon did? ^^
