### ISSUE TITLE
White dots when using in Forge with Sinytra Connector

### ISSUE THREAD

**Issue by MindSetFPS** [MCRcortex/nvidium#171]
I have been using the method mentioned in this [reddit thread](https://www.reddit.com/r/allthemods/comments/199sm7i/comment/kihjyak/) to play Nvidium in Forge and I noticed that some white dots appear in the world.

In the Embeddium github this bug [is mentioned](https://github.com/embeddedt/embeddium/issues/208#issuecomment-1949001234) and there is also a fix, but when using Nvidium, the fix does not work.

Diabling Nvidium in the settings tab does not fix it, the mod must be removed to eliminate said white dots.

It may be possible that it should be fixed by Sodium or Embeddium first, but im posting here because the suggested fix does not work when using Nvidium, probably due to the way "Compact Vertex Format" feature is used.

**Comment by Briarbot2011** [comment]
forge isn't supported, nvidium is built for fabric.

**Comment by Tapacywka** [comment]
https://github.com/ferriarnus/acedium
Nvidium fork for NeoForge & Embeddium
