### ISSUE TITLE
[Linux] JRE fatal error when quitting game

### ISSUE THREAD

**Issue by DarkblooM-IO** [MCRcortex/nvidium#172]
I installed the mod and noticed Minecraft started closing with a JRE crash. It's not that annoying since it occurs when the game closes but it's still a crash so I figured I'd share it.

Minecraft logs don't say anything related to this, however here's the JRE error message:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000074baec8f5882, pid=4029, tid=4030
#
# JRE version: OpenJDK Runtime Environment 21.9 (17.0.9+7) (build 17.0.9+7)
# Java VM: OpenJDK 64-Bit Server VM 21.9 (17.0.9+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.550.54.14+0x6f5882]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /home/darkbloom/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/fabricated/.minecraft/core.4029)
#
# An error report file with more information is saved as:
# /home/darkbloom/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/fabricated/.minecraft/hs_err_pid4029.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
```

**Comment by BrycensRanch** [comment]
welcome to the club. I doubt this has anything to do with the mod itself

for example I am using the fabously optimized modpack which doesn't make use of this mod and I still get the error + hanging lol
```
[01:44:59] [Render thread/INFO]: closing rrp ebe:base_resources
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGBUS (0x7) at pc=0x00007f7b8d7d4cfc, pid=17547, tid=17555
#
# JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.10.0.7-3) (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.10.0.7-3) (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  [libnvidia-glcore.so.550.67+0x9d4cfc]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /run/media/romvnly/263cdc07-046f-49d4-a45b-29b0e3e82f57/home/romvnly/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/core.17547)
#
# An error report file with more information is saved as:
# /run/media/romvnly/263cdc07-046f-49d4-a45b-29b0e3e82f57/home/romvnly/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/hs_err_pid17547.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=38
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process was killed by user.

**Comment by DarkblooM-IO** [comment]
> welcome to the club. I doubt this has anything to do with the mod itself
> 
> for example I am using the fabously optimized modpack which doesn't make use of this mod and I still get the error + hanging lol
> 
> ```
> [01:44:59] [Render thread/INFO]: closing rrp ebe:base_resources
> #
> # A fatal error has been detected by the Java Runtime Environment:
> #
> #  SIGBUS (0x7) at pc=0x00007f7b8d7d4cfc, pid=17547, tid=17555
> #
> # JRE version: OpenJDK Runtime Environment (Red_Hat-17.0.10.0.7-3) (17.0.10+7) (build 17.0.10+7)
> # Java VM: OpenJDK 64-Bit Server VM (Red_Hat-17.0.10.0.7-3) (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
> # Problematic frame:
> # C  [libnvidia-glcore.so.550.67+0x9d4cfc]
> #
> # Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /run/media/romvnly/263cdc07-046f-49d4-a45b-29b0e3e82f57/home/romvnly/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/core.17547)
> #
> # An error report file with more information is saved as:
> # /run/media/romvnly/263cdc07-046f-49d4-a45b-29b0e3e82f57/home/romvnly/.local/share/PrismLauncher/instances/Fabulously Optimized/.minecraft/hs_err_pid17547.log
> #
> # If you would like to submit a bug report, please visit:
> #   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-17-openjdk&version=38
> # The crash happened outside the Java Virtual Machine in native code.
> # See problematic frame for where to report the bug.
> #
> Process was killed by user.
> ```

That's odd, I only ever experience this when using Nvidium. Thanks for sharing.

**Comment by Xenonus** [comment]
Adding `__GL_THREADED_OPTIMIZATIONS=0` to environment variables fixed the issue for me. It's an Nvidia driver issue
