### ISSUE TITLE
Error in water rendering?

### ISSUE THREAD

**Issue by NNON0STOP** [MCRcortex/nvidium#174]
https://github.com/MCRcortex/nvidium/assets/163924154/2342236a-d84d-4598-acf2-138c619735dd

how to fix it

**Comment by KarmaMarazu** [comment]
does it happen when going over a chunk border? and what do the logs say? can you recreate it or did it only happen this time and reloading mc "fixes" it?

**Comment by NNON0STOP** [comment]
No, restarting Minecraft doesn't help. and this happens when I enter the ocean biome. unfortunately I don’t know how to view the logs, sorry

**Comment by KarmaMarazu** [comment]
locate your .minecraft folder (on windows for the vanilla launcher its %appdata% from there look for .minecraft) in there there is a folder called logs then send the latest log (please use mclo.gs) also what mods do you have?

**Comment by NNON0STOP** [comment]
i need to send a link?

**Comment by KarmaMarazu** [comment]
yes

**Comment by NNON0STOP** [comment]
https://mclo.gs/7SYrv9O 
and my mods 
![Снимок экрана 2024-03-19 001518](https://github.com/MCRcortex/nvidium/assets/163924154/ce7d311d-89c1-463c-abb0-b5e33d91e5fd)
![Снимок экрана 2024-03-19 001533](https://github.com/MCRcortex/nvidium/assets/163924154/3a2faa97-6c5a-40d8-9781-95eb055db89f)
![Снимок экрана 2024-03-19 001543](https://github.com/MCRcortex/nvidium/assets/163924154/737832c4-578a-4fce-a4e2-3f98cbc1c74a)
![Снимок экрана 2024-03-19 001558](https://github.com/MCRcortex/nvidium/assets/163924154/9aefee6a-2a1f-4d60-b78c-83a0bfe6f4d6)
![Снимок экрана 2024-03-19 001618](https://github.com/MCRcortex/nvidium/assets/163924154/397788d9-a0fc-426c-bb69-e273e5172eee)
![Снимок экрана 2024-03-19 001744](https://github.com/MCRcortex/nvidium/assets/163924154/e0bff660-f6b2-4fcb-91c6-b0d639f30ae4)

**Comment by KarmaMarazu** [comment]
a quick look i cant see a nvidium error it could be one of the *MANY* other mods have u tried removing nvidium/other mods (thanos method maybe remove half see if its fixed if not remove half again or if it is add half till u find the mod thats weird)

**Comment by NNON0STOP** [comment]
Well, I realized that it was Nvidium, because I turned it off in the settings and the textures became normal. I have a guess about Starlight and some other mods

**Comment by NNON0STOP** [comment]
anyway thank you for the explanation and help

**Comment by NNON0STOP** [comment]
I found a mod that causes this error it was Hybrid Aquatic
