### ISSUE TITLE
The light source processing of LambDynamicLights is faulty

### ISSUE THREAD

**Issue by Memory-Yzf** [MCRcortex/nvidium#175]
See the video for details.
On the right side of the screen is a list of mods.

https://github.com/MCRcortex/nvidium/assets/102323087/340cf2b2-1add-43b1-b9b4-7ae5b60245fe

**Comment by xnousnow** [comment]
I don't really see any problems there..?

**Comment by UrBoiTom** [comment]
> I don't really see any problems there..?

The light is flickering with NVIDIUM turned on

**Comment by Memory-Yzf** [comment]
The refresh rate of the light source is delayed.



Pay attention to the light source on the ground.




---Original---
From: ***@***.***&gt;
Date: Fri, Mar 29, 2024 19:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MCRcortex/nvidium] The light source processing ofLambDynamicLights is faulty (Issue #175)




  
I don't really see any problems there..?
  
The light is flickering with NVIDIUM turned on

**Comment by JoeyHamlet** [comment]
I've noticed this issue for a while, didn't realise it was due to Nvidium until now though. Appreciate the confirmation.

**Comment by 1625926165** [comment]
> I've noticed this issue for a while, didn't realise it was due to Nvidium until now though. Appreciate the confirmation.

I'm glad you identified the problem. I hope it can be resolved
