### ISSUE TITLE
Player blind in nether

### ISSUE THREAD

**Issue by OriganalAndCreativeName** [MCRcortex/nvidium#176]
You cannot see anything in the nether unless it is far away. The fog seems to be inverted (it coverers blocks close to you but not those far away) To recreate this just go into the nether with invidium active and its region keep distance set above 120 chunks. This is in minecraft 1.21

**Comment by dangerbritson** [comment]
Same for overworld whenever it rains, the fog inverts and I can only see things that are far away instead of nearby.

**Comment by Colaskink** [comment]
See #131  , i had the same issue.

**Comment by KarmaMarazu** [comment]
Same as #131
