### ISSUE TITLE
Implement ReStir global illumination

### ISSUE THREAD

**Issue by vertexgamer** [MCRcortex/nvidium#177]
Not sure how hard it would be to implement restir on opengl, but since most of the pipeline is ran on the gpu anyway, it might be easier to natively implement RestirGI then support for various shaders

**Comment by FluffyPuppyKasey** [comment]
ReSTIR does not run on OpenGL. It would have to be a completely custom implementation and wouldn't even be worth it for Nvidium, as it's focused on performance and not raytracing
