### ISSUE TITLE
Slight block update delay when interacting with the world.

### ISSUE THREAD

**Issue by noahnao** [MCRcortex/nvidium#178]
I've noticed a slight block update delay when interacting with the world while using the [Mod Name] mod. When I place or break blocks, there's a noticeable delay before the changes take effect visually. This delay seems to affect both single-player and multiplayer modes.

Steps to Reproduce:

1.  Install the mod Nvidium 0.2.6-beta.
2.  Start a new game or join a multiplayer server.
3. Attempt to break blocks rapidly.
4. Observe the delay between the action and the visual update of the affected blocks.

Expected Behavior:
When placing or breaking blocks, I expect the changes to take effect immediately, without any noticeable delay. This ensures smooth gameplay and prevents any frustration caused by delays in block updates.

Actual Behavior:
There's a slight delay between performing actions such as placing or breaking blocks and the visual update of the affected blocks. This delay disrupts the flow of gameplay and can be particularly noticeable during fast-paced building or mining sessions.

Additional Information:
I've attached a video showcasing the issue for reference: [Video_Link]. Please note the delay between the block placement/breaking action and the actual update of the affected blocks.

https://github.com/MCRcortex/nvidium/assets/81416193/47c93ae5-af90-466b-8620-8ee7633a5c27

Mod Version: 0.2.6-beta.

Minecraft Version: 1.20.4

Operating System: Windows

This issue affects the overall gameplay experience, and I believe addressing it would greatly improve the usability and enjoyment of the Nvidium. If any further information is needed, please let me know. Thank you for your attention to this matter.

(It might be an incompatibility with my other mods, but concluded that this behavior is exclusive to Nvidium, because when I tried to troubleshoot this problem I tried disabling my fabric mods to figure out what mod was causing this, and it stopped when I got to disabling Nvidium)
so here is the mods list:

1. threadtweak-fabric-1.20.4-0.1.2.jar
2. tia-1.20-1.1-fabric.jar
3. visuality-0.7.4+1.20.4.jar
4. vmp-fabric-mc1.20.4-0.2.0+beta.7.138-all.jar
5. yet-another-config-lib-fabric-3.3.2+1.20.4.jar
6. yosbr-0.1.2.jar
7. YungsApi-1.20.4-Fabric-4.4.2.jar 
8. Zoomify-2.13.1.jar
9. accurate-block-placement-1.2.1.jar
10. AdvancementPlaques-1.20.4-fabric-1.5.1.jar
11. AmbientEnvironment-fabric-1.20.4-14.0.0.3.jar
12. AmbientSounds_FABRIC_v5.3.5_mc1.20.4.jar
13. appleskin-fabric-mc1.20.3-2.5.1.jar
14. ash_api-fabric-20.4.0.jar
15. auditory-0.0.6-1.20.4.jar
16. BadOptimizations-2.1.0.jar
17. balm-fabric-1.20.4-9.0.6.jar
18. BetterAdvancements-Fabric-1.20.4-0.4.1.5.jar
19. betterbeds-1.3.0-1.19.3.jar
20. BetterF3-9.0.2-Fabric-1.20.4.jar
21. BetterLineBreak-1.20.4(Fabric)-1.1.0.jar
22. BetterThirdPerson-Fabric-1.20-1.9.0.jar
24. blur-3.2.0.jar
25. bobby-5.1.0+mc1.20.4.jar
26. Bookshelf-Fabric-1.20.4-23.0.6.jar
27. c2me-fabric-mc1.20.4-0.2.0+alpha.11.61.jar
28. camerautils-fabric-1.20.4-1.0.9.jar
29. chat_heads-0.10.32-fabric-1.20.3.jar
30. clean_tooltips-1.0-fabric-1.20.4.jar
31. ClientHarvest-1.0.4.jar
32. clienttweaks-fabric-1.20.4-13.0.2.jar
33. cloth-config-13.0.121-fabric.jar
34. collective-1.20.4-7.40.jar
35. completeconfig-2.5.3.jar
36. continuity-3.0.0-beta.4+1.20.2.jar
37. Controlling-fabric-1.20.4-15.0.3.jar
38. CreativeCore_FABRIC_v2.11.16_mc1.20.4.jar
39. cubes-without-borders-1.1.0+1.20.jar
40. CullLessLeaves-1.3.0.jar
41. Debugify-1.20.4+1.1.jar
42. DisableCustomWorldsAdvice-5.0.jar
43. DripSounds-1.19.4-0.3.2.jar
44. dynamic-fps-3.4.2+minecraft-1.20.4-fabric.jar
45. eating-animation-1.20+1.9.61.jar
46. EnchantmentDescriptions-Fabric-1.20.4-20.0.2.jar
47. enhancedblockentities-0.9.1+1.20.2.jar
48. entity_model_features_fabric_1.20.4-1.3.jar
49. entity_texture_features_fabric_1.20.4-5.2.3.jar
50. entityculling-fabric-1.6.4-mc1.20.4.jar
51. fabric-api-0.96.11+1.20.4.jar
52. fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
53. fallingleaves-1.15.6+1.20.1.jar
54. ferritecore-6.0.3-fabric.jar
55. ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar
56. FreshAnimations_v1.9.zip
57. Iceberg-1.20.4-fabric-1.1.18.jar
58. ImmediatelyFast-Fabric-1.2.11+1.20.4.jar
59. indium-1.0.30+mc1.20.4.jar
60. InvMove-1.20-0.8.5-Fabric.jar
61. iris-mc1.20.4-1.6.16.jar
62. krypton-0.2.6.jar
63. lambdynamiclights-2.3.4+1.20.4.jar
64. language-reload-1.5.10+1.20.3.jar
65. lazydfu-0.1.3.jar
66. LeaveMyBarsAlone-v20.4.1-1.20.4-Fabric.jar
67. LetSleepingDogsLie-1.20.4-Fabric-1.2.0.jar
68. lithium-fabric-mc1.20.4-0.12.1.jar
69. make_bubbles_pop-0.2.0-fabric-mc1.19.4+.jar
70. memoryleakfix-fabric-1.17+-1.1.5.jar
71. modelfix-1.14-fabric.jar
72. modernfix-fabric-5.15.0+mc1.20.4.jar
73. modmenu-9.0.0.jar
74. morechathistory-1.3.0.jar
75. moreculling-1.20.4-0.22.1.jar
76. MouseTweaks-fabric-mc1.20-2.26.jar
77. mousewheelie-1.13.3+mc1.20.4.jar
78. NoChatReports-FABRIC-1.20.4-v2.5.0.jar
79. noisium-1.0.2+mc1.20.x.jar
80. notenoughanimations-fabric-1.7.1-mc1.20.4.jar
81. nvidium-0.2.6-beta.jar
82. physics-mod-pro-v167d-fabric-1.20.4.jar
83. PresenceFootsteps-1.11.3.jar
84. PuzzlesLib-v20.4.42-1.20.4-Fabric.jar
85. reeses_sodium_options-1.7.2+mc1.20.4-build.102.jar
86. Searchables-fabric-1.20.4-1.0.6.jar
87. shuffle-fabric-20.4.1.jar
88. shulkerboxtooltip-fabric-4.0.8+1.20.4.jar
89. skinlayers3d-fabric-1.6.2-mc1.20.4.jar
90. SmoothScrollingRefurbished+1.20.4-1.1.2.jar
91. sodium-extra-0.5.4+mc1.20.4-build.116.jar
92. sodium-fabric-0.5.8+mc1.20.4.jar
93. sodium-shadowy-path-blocks-3.2.1.jar
94. sound-physics-remastered-fabric-1.20.4-1.3.1.jar
95. starlight-1.1.3+fabric.f5dcd1a.jar
96. StylishEffects-v20.4.2-1.20.4-Fabric.jar

**Comment by KarmaMarazu** [comment]
This seems to be the same issue as #156

**Comment by noahnao** [comment]
> This seems to be the same issue as #156

Yeah, I think it is the same.
