### ISSUE TITLE
Possible formula for max render distance with Nvidium

### ISSUE THREAD

**Issue by FASTB1mc** [MCRcortex/nvidium#183]
I learned about Nvidium from Purplers's video on it and in the video he said that he could not push his render distance above 88 chunks or it would get laggy. Because Nvidium uses v-ram to load chunks, I found that Purplers's RTX 3080 GPU has 10 GB of v-ram. So I divided 88 by 10 to get 8.8. Now take that 8.8 and multiply it by the amount of v-ram your have and it should be your max render distance. 

Simplified, the formula is 8.8 time the amount of v-ram you have to get your maximum render distance. Also the number you get is usually a number with a decimal so round down.

**Comment by Vricken** [comment]
I don't know anything about modding but the number of chunks loaded scales quadratically with the render distance (as the area is pi*r^2) so any formula that doesn't consider this can't possibly work. Plus there are so many factors that a formula wouldn't be the best course of action, just crank the render distance up till it lags and move it down until you have an amount of fps you are happy with.

**Comment by FASTB1mc** [comment]
Ok. I have an Nvidia RTX 4070 for laptops and I was able to get to 100 chunks and still have 200 FPS to spare. I also have a lot of other performance mods.

**Comment by FASTB1mc** [comment]
Thank you BTW
