### ISSUE TITLE
Nvidium Doesn't use all the graphics memory 

### ISSUE THREAD

**Issue by davethepommes** [MCRcortex/nvidium#185]
I have a RTX 3050 (on Desktop) and the graphics card has a total of 8 GB of VRAM and Nvidium only uses 2 GB of VRAM and I can't set it manually how much VRAM Nvidium should use.

**Comment by KarmaMarazu** [comment]
There is a setting you have to click to manually change it byt by default it auto uses what it can even when the crossed through looks like it uses 2

**Comment by davethepommes** [comment]
ok i'll try it when i have time.
Thanks for the quick help I didn't think it would happen so quickly :)

**Comment by KarmaMarazu** [comment]
Np it should be fine without any changes and there is a bot in the discord that shows all bug reports and comits etc so it can be seen when someone opens a new issue if i know/understand whats going on i like to help out here and there
