### ISSUE TITLE
1.20.6

### ISSUE THREAD

**Issue by PukPukov** [MCRcortex/nvidium#186]

**Comment by KarmaMarazu** [comment]
https://github.com/MCRcortex/nvidium/pull/184#issuecomment-2092186868 issue 184 and it has already been merged may i recommend for next time to check previous issues to not make ones that have already happened?

**Comment by PukPukov** [comment]
>may i recommend for next time to check previous issues to not make ones that have already happened

I am generally checking, right now i just forgot.
