### ISSUE TITLE
New NVIDIA driver causing chunks to flicker?

### ISSUE THREAD

**Issue by aiyafps** [MCRcortex/nvidium#19]
Updated to the newest NVIDIA driver (531.79) an hour ago and since then I'm getting flickering in chunks below me, when I remove Nvidium from mod my list the flickering stops!

**Comment by OmegaPhoenix637** [comment]
I also get flickering of texures on mccisland

**Comment by Username404-59** [comment]
I also have this issue on linux with the 535.43.02 drivers, and it happens on all servers including singleplayer
Here's a video of it:

https://github.com/MCRcortex/nvidium/assets/53659497/61899b45-5b20-46cc-93a4-4b53fc21ff1a

**Comment by CrabbyDisk** [comment]
I also have this issue on linux. Here is useful information.
GPU: RTX 3060 Ti
Driver version: 535.54
OpenGL version: 4.6.0
Kernel: zen 6.3.8
Note that this only happens near the ground.

**Comment by alvesvaren** [comment]
Yeah this is happening to me too, gpu: 3070 ti nvidia: 535.54 kernel: lqx 6.3.9

**Comment by forkiesassds** [comment]
Can reproduce on a 3060 with 535.54.03 drivers on kernel 6.4.1

**Comment by emortaldev** [comment]
Can reproduce on 2060 super with 535.54.03 drivers on kernel 6.3.10

**Comment by enginelesscc** [comment]
Can **not** reproduce with beta driver 545.31 on W11 insider build 25393.1
Everything renders correctly

**Comment by Username404-59** [comment]
> Can **not** reproduce with beta driver 545.31 on W11 insider build 25393.1 Everything renders correctly

Yeah it is an issue specific to the linux nvidia beta drivers (and probably on nvidia's side)
I've checked and the 525.125.06 drivers work fine

**Comment by Inconn** [comment]
can reproduce on 3070 with 535.54.03 drivers on arch linux-zen kernel 6.4.3
seems specific to linux

**Comment by Inconn** [comment]
https://youtu.be/CEg-_x7aYJ8 here's another video of it happening
it seems that it only flickers things in the chunk you're in that you're close to. also it can flicker stuff above you

**Comment by MCRcortex** [comment]
this is apparently caused by nvidias threaded optimizations, if you disable them apparently it fixes it

**Comment by Inconn** [comment]
can confirm, disabling threaded optimizations fixes it
![disable_threaded](https://github.com/MCRcortex/nvidium/assets/62788103/a6052642-7c1f-48b8-952f-16e8273362a8)

**Comment by forkiesassds** [comment]
nvidium 0.1.15 and Nvidia 535.86.05 driver no longer seem to have the issue. Although it could also be that they have disabled threaded optimizations or the launcher I'm using bypasses them

**Comment by MCRcortex** [comment]
Fix was applied in 0.1.15 (and by fix i mean disabling threaded optimization using enviroment variable)
