### ISSUE TITLE
LittleTiles incompatibility

### ISSUE THREAD

**Issue by MichelJonkman** [MCRcortex/nvidium#194]
I'm using Nvidium 0.2.6 on forge through the use of [Acedium](https://github.com/ferriarnus/acedium) and Sinytra Connector together with LittleTiles and a minor rendering bug popped up. Note that this works absolutely perfectly in every other way so it doesn't seem like an issue with Acedium/Connector.

Now I know this is very much in the realm of unsupported but I would really appreciate it if it could be looked at and either fixed in Nvidium or with enough information I could tell the developer of LittleTiles what needs to be changed to fix it.

The bug is that things like doors in animations are invisible, easiest reproduction is to just create a simple door. If needed I can provide a MultiMC/Prism instance with a world included.

**Comment by MrCatlio** [comment]
try without the Sinytra connector since when i tried Acedium (Nvidium) with the mod LittleTiles the game would work and have no issues but i would recommend waiting for the release of LittleTiles since it could be a issue with a different mod which could be causing the issue.

**Comment by MichelJonkman** [comment]
@MrCatlio What versions are you using? And are you sure Nvidium isn't disabled? Even with a minimal modlist the animations are invisible

**Comment by MrCatlio** [comment]
i used the latest version of LittleTiles and no nvidium was not disabled i had to use an older version of Embeddium since the latest version has issue with Acedium

**Comment by MrCatlio** [comment]
Littletiles has some items that is causing the game to crash i didnt have nvidium enabled

**Comment by MrCatlio** [comment]
Theses are the mods that im using. (the crash log on when it crashed)

![image](https://github.com/MCRcortex/nvidium/assets/59648425/3dac2a75-be79-46de-a243-b24cf3579746)
![image](https://github.com/MCRcortex/nvidium/assets/59648425/c3236ed1-1d2b-42b8-a266-c0c532802063)

**Comment by MichelJonkman** [comment]
@MrCatlio Could you post the version numbers too?

**Comment by MrCatlio** [comment]
![image](https://github.com/MCRcortex/nvidium/assets/59648425/20fcfe4e-9339-42c7-801c-3f676bc4a389)

**Comment by MrCatlio** [comment]
but you might want to wait for the release since by the look of the github repo there are a couple of reports of people having issues with the mod

**Comment by ferriarnus** [comment]
So the only thing that comes to mind would be a render solution that is similar to valkery skies and renders it in some far away chunks. That breaks since nvidium simply culls these chunks out (I looked for a solution but didn't find a simple one)

Briefly looking at their code, yes this is what they do... The real solution here is to mark these chunks as "always render" and exclude them from the culling (don't ask me *how*, I haven't looked deep enough to be able to fix it)

**Comment by MichelJonkman** [comment]
> but you might want to wait for the release since by the look of the github repo there are a couple of reports of people having issues with the mod

Yeah I've had a few issues but not much concerning the core parts I want to use, I'll try your list and report back later!

**Comment by MichelJonkman** [comment]
I don't think anything but Nvidium or LittleTiles can fix this issue. If there's anything I need to pass forward to the LittleTiles developer for him to do I can!
