### ISSUE TITLE
Does rendering not work?

### ISSUE THREAD

**Issue by Spturate** [MCRcortex/nvidium#195]
my graphics card is RTX3060 Laptop, and the driver is the latest. Does this rendering not work?
![屏幕截图 2024-05-24 224640](https://github.com/MCRcortex/nvidium/assets/30800649/e82f8076-5fae-45c0-925e-54bd502b79cc)
![屏幕截图 2024-05-24 224716](https://github.com/MCRcortex/nvidium/assets/30800649/63296fb3-f23d-41d7-847e-cd5089eab87d)
[latest.log](https://github.com/MCRcortex/nvidium/files/15441584/latest.log)

**Comment by MrCatlio** [comment]
try changing your simulation distance since it will only render what has been loaded by the built in server (Single Player World)

**Comment by Andarwinux** [comment]
You should also install C2ME to unlock rendering and simulation distances, as well as increase memory allocation for JVM as appropriate.
