### ISSUE TITLE
1.20.5

### ISSUE THREAD

**Issue by FASTB1mc** [MCRcortex/nvidium#197]
Where is Nvidium for 1.20.5?

**Comment by KarmaMarazu** [comment]
https://modrinth.com/mod/nvidium/version/0.2.7-beta please read before u post something its right on modrinth and no dont say but it says 1.20.6 as 1.20.6 has just 1 bugfix more then 1.20.5 and is 99.999999% compatible with 1.20.5 mods but like there is no reason to play 1.20.5 if 1.20.6 exists
