### ISSUE TITLE
compat with new version

### ISSUE THREAD

**Issue by Emil2010** [MCRcortex/nvidium#199]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.9+mc1.20.6 with version 0.5.8.
More details:
	 - Mod 'Indium' (indium) 1.0.31+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	 - Mod 'Nvidium' (nvidium) 0.2.7-beta requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

iris shaders and sodium extra support new version of sodium
same issue has been posted to indium's issue tracker

**Comment by fuze-zy** [comment]
try using the following versions for iris, sodium, and nvidium respectively:
- 1.70+1.20.6
- mc1.20.6-0.5.8
- 0.2.7-beta
these worked for me with additional mods as well, so you can try them

**Comment by NolanHewitt** [comment]
New version of sodium 0.5.10 is marked as incompatible. Not sure if an update is needed or if the version numbering in fabric.mod.json just needs to be changed
