### ISSUE TITLE
MCCI getting lines around blocks and sometimes a flashy screen

### ISSUE THREAD

**Issue by OmegaPhoenix637** [MCRcortex/nvidium#2]
https://i.imgur.com/pEoAx27.png
I get white lines when I go on mcci, but I dont when I am in a normal world, probably something to do with the resourcepack, and sometimes when I just walk around my screen will flash and then go back to normal.

**Comment by R00tB33rMan** [comment]
> https://i.imgur.com/pEoAx27.png I get white lines when I go on mcci, but I dont when I am in a normal world, probably something to do with the resourcepack, and sometimes when I just walk around my screen will flash and then go back to normal.

Can reproduce, on top of this unusual occurrence: 
![2023-04-17_14 14 22](https://user-images.githubusercontent.com/36140389/232574329-2a4b4ea5-5b64-468e-a995-9eb1e8f70b0c.png)

**Comment by MCRcortex** [comment]
Fixed with https://github.com/MCRcortex/nvidium/commit/8ee7bc91fe43d0252c0211d422a4aab3eb6234d5
