### ISSUE TITLE
Partial incompatibility with Distant Horizons

### ISSUE THREAD

**Issue by Leva25se** [MCRcortex/nvidium#20]
Some regions display one regions with LOD Distant Horizons chunks, while in other regions only two region with LOD chunks is visible. In some regions, all LOD chunks are visible. It is not clear to me by what principle LOD regions are visible or not.
One visible:
<img src="https://github.com/MCRcortex/nvidium/assets/125301618/949c7030-e7cd-4c8f-8385-92053b84d122" width=50% height=50%><img src="https://github.com/MCRcortex/nvidium/assets/125301618/a841d921-799c-46ce-9e80-613a372508c2" width=50% height=50%>
Two or more visible:
<img src="https://github.com/MCRcortex/nvidium/assets/125301618/1f49a1bb-3227-4998-b86c-fc776fd68748" width=50% height=50%><img src="https://github.com/MCRcortex/nvidium/assets/125301618/ed1772ad-f618-4721-a472-44080cd925e3" width=50% height=50%>
Mod versions:
Distant Horizons: 1.6.11a
nvidium: 0.1.10-alpha
Sodium: 0.4.11+build.26

**Comment by MikiP98** [comment]
I've had the same issue with Distant Horizons on 1.19.3 without Nvidium. Unfortunately, I don’t remember how I fixed it, but I don’t think it’s caused by NVidium or at least not only by it.
