### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by ghost** [MCRcortex/nvidium#202]
Just a reminder new update is out, idk if changing the fabric mod json would work, but it's worth a shot if the update isn't out yet.

**Comment by ghost** [comment]
You mean 1.21? Not 1.20.6

**Comment by ghost** [comment]
> You mean 1.21? Not 1.20.6

yup fixed

**Comment by Aertic** [comment]
It isnt compatible with sodium 0.5.9, so I assume you'd need to do something more

**Comment by pizzav-xyz** [comment]
is there a roadmap?

**Comment by KarmaMarazu** [comment]
solved

**Comment by Aertic** [comment]
Solved
