### ISSUE TITLE
Nvidium shaders.

### ISSUE THREAD

**Issue by spidercraft** [MCRcortex/nvidium#203]
what is annoying is that distant horizon wich use it's own method to render chunks have compatibility with shaders, so why wouldn't it be possible with nvidium?

**Comment by KarmaMarazu** [comment]
they are 2 completely different things
they work in completely different ways and are not comparable

**Comment by Kiszak** [comment]
bro

**Comment by Aertic** [comment]
please think about what you just said

**Comment by spidercraft** [comment]
> they are 2 completely different things they work in completely different ways and are not comparable

rip, in that case nvidium is pretty much useless ig

**Comment by KarmaMarazu** [comment]
> rip, in that case nvidium is pretty much useless ig

wot? shaders ≠ usefulness

**Comment by CarlosBTav** [comment]
Sadly it's true for a lot of people that just want to play with shaders(I would never play without shaders) so NVIDIUM and chunky is useless for me and these lot of people who need to use shaders.

**Comment by Aertic** [comment]
Tbh I also prefer shaders but still keep nvidium for when i turn them off and such. But yea, not supporting shaders makes it useless for the majority of people

**Comment by KarmaMarazu** [comment]
I wouldn't say majority i dont think a majority of people run shaders

**Comment by spidercraft** [comment]
Actually we do. Most of the people playing minecraft for it's survival aspect and not minigame such as hypixel. We basically all use shaders wich means that the only use case for nvidium is servers like hypixel for pvp / minigames. Idk if there is a discord for nvidium but if there is y'all should definetely do a poll to ask how many people use shaders.

**Comment by KarmaMarazu** [comment]
yes there is a discord but no i think ur very much over estimating how many people use shaders because you and some of ur friends do does not mean most do

**Comment by spidercraft** [comment]
most of the people that dont use shaders don't do it because it is too performance heavy wich is why nvidium would be a good use for it. Also out of curiosity, even if it would not be able to support shaders that work with iris currently, would it be theoretically possible to make "nvidium only shaders"? It would not be perfect but would be wayyy better already

( just to make it clear im not shitting on nvidium as it is useful for some people. Im simply pointing out that shader compatibility is a big thing )

i mean look how many members iris has and how big of a deal it was for iris to come to fabric since before that there was no shaders for fabric

**Comment by KarmaMarazu** [comment]
> rip, in that case nvidium is pretty much useless ig

> ( just to make it clear im not shitting on nvidium as it is useful for some people. Im simply pointing out that shader compatibility is a big thing )

what? thats literally what ur saying lmao
also no just stop

**Comment by CrabbyDisk** [comment]
> most of the people that dont use shaders don't do it because it is too performance heavy wich is why nvidium would be a good use for it. Also out of curiosity, even if it would not be able to support shaders that work with iris currently, would it be theoretically possible to make "nvidium only shaders"? It would not be perfect but would be wayyy better already
> 
> ( just to make it clear im not shitting on nvidium as it is useful for some people. Im simply pointing out that shader compatibility is a big thing )
> 
> i mean look how many members iris has and how big of a deal it was for iris to come to fabric since before that there was no shaders for fabric

Just go use Distant Horizons at this point if you really need shaders. Nvidium never was designed to support shaders, and that's one of the reasons why it performs so well.

**Comment by spidercraft** [comment]
> Sadly it's true for a lot of people that just want to play with shaders(I would never play without shaders) so NVIDIUM and chunky is useless for me and these lot of people who need to use shaders.

yeah, useless for me and a lot of people. Not useless for EVERYONE

**Comment by Earthcomputer** [comment]
Don't use it then? No need to complain here. Cortex hasn't decided to not support shaders because she doesn't like them, it's for technical reasons a hard thing to implement.

**Comment by KarmaMarazu** [comment]
> yeah, useless for me and a lot of people. Not useless for EVERYONE

then say useless for you

MOST people who play minecraft DONT use shaders this is a FACT so STOP saying for A LOT of people its for a group of players

iris has ~9 mil downloads on modrinth many people have downloaded it multiple times but lets say 9 cuz thats also not counting cf and github etc

minecraft has sold over 300 mil times thats quite a bit bigger

**Comment by CarlosBTav** [comment]
> > Sadly it's true for a lot of people that just want to play with shaders(I would never play without shaders) so NVIDIUM and chunky is useless for me and these lot of people who need to use shaders.
> 
> yeah, useless for me and a lot of people. Not useless for EVERYONE

I never said it's useless for everyone, just for a big portion of users. I still encourage the developer to keep working on it and hope a lot of people enjoy it. I was just commenting my experience with the shader, but I'm still here interested in seeing where it goes because in a lot of ways is even better than DH so I wish the well to this mod.

**Comment by spidercraft** [comment]
I didn't knew voxy existed but since voxy gives similar results to nvidium while half supporting shaders im gonna mark this as closed!

( for anyone in the same situation as me that wants a mod similar to nvidium while working with shaders then use voxy! Works good with complementary shaders and around 20 chunks +. )

https://github.com/MCRcortex/voxy
