### ISSUE TITLE
Nvidium for Sodium 0.5.10 on 1.20.1

### ISSUE THREAD

**Issue by monstercatyy** [MCRcortex/nvidium#205]
This issue is to track progress and discuss the compatibility of Nvidium with Sodium version 0.5.10 on Minecraft 1.20.1. As Sodium 0.5.10 has been a major update with breaking changes, it's important to ensure Nvidium functions as intended with this new version.

**Key Points for Discussion:**

- Current Status: Is there a working version of Nvidium compatible with Sodium 0.5.10? _No_

- Known Issues: Have any specific problems or bugs been encountered when trying to use Nvidium with the updated Sodium? _Incompatible with Sodium 0.5.10_

- Development Progress: Are there any active efforts to update Nvidium for compatibility?

- Workarounds: Are there any temporary solutions or adjustments users can make to get Nvidium working (if possible)? _Can't find any_

**Comment by KarmaMarazu** [comment]
same as #204 i posted a solution there

https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2179907629

**Comment by MrCatlio** [comment]
> This issue is to track progress and discuss the compatibility of Nvidium with Sodium version 0.5.10 on Minecraft 1.20.1. As Sodium 0.5.10 has been a major update with breaking changes, it's important to ensure Nvidium functions as intended with this new version.
> 
> **Key Points for Discussion:**
> 
> * Current Status: Is there a working version of Nvidium compatible with Sodium 0.5.10? _No_
> * Known Issues: Have any specific problems or bugs been encountered when trying to use Nvidium with the updated Sodium? _Incompatible with Sodium 0.5.10_
> * Development Progress: Are there any active efforts to update Nvidium for compatibility?
> * Workarounds: Are there any temporary solutions or adjustments users can make to get Nvidium working (if possible)? _Can't find any_

Theses are known to work currently for 1.20.1
Sodium: 0.5.7
Sodium Extras: 0.5.4
Nvidium: 0.2.6

**Comment by stranger1200** [comment]
For anyone interested I've made a fork that fixes this: 
https://github.com/stranger1200/nvidium

The main gist is that getEncoder() needed to be updated to loop over 
the new Vertex[] array rather than handling a single vertex per call. 
Precompiled JAR is in the releases if you don't want to build it yourself.
