### ISSUE TITLE
The mod is requesting a outdated version of Sodium

### ISSUE THREAD

**Issue by StrangeCorvus** [MCRcortex/nvidium#207]
I keep getting this message:

> "Replace mod 'Nvidium' (nvidium) 0.2.7-beta with any version that is compatible with: 
>
> _sodium 0.5.9+mc1.20.6_"
>
> Mod 'Nvidium' (nvidium) 0.2.7-beta requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 
>
> _0.5.9+mc1.20.6!_

I think the mod is trying to use the previous version, i tried downgrading sodium but that breaks all my other mods because they all use 0.5.9

I thought about manually downgrading all the mods that use sodium, but most of them don't have a version that uses 0.5.8

**Comment by KarmaMarazu** [comment]
try reading the previous 3 (#204 #205 #206) issues before making a new one 
(it has the same solution)
