### ISSUE TITLE
Support for Sodium 0.5.9

### ISSUE THREAD

**Issue by BenjaminHoegh** [MCRcortex/nvidium#209]
Please add support for Sodium 0.5.9 (sodium-fabric-0.5.9+mc1.20.6.jar)

**Comment by Viper4K** [comment]
that, and 0.5.10, since it would help alot with the new distant horizons update (which requires 0.5.10)
and yes, i know, you can change the required version in nvidium file, but i would like to see an official support instead of make-do solution...

**Comment by Skywalker8510** [comment]
> that, and 0.5.10, since it would help alot with the new distant horizons update (which requires 0.5.10) and yes, i know, you can change the required version in nvidium file, but i would like to see an official support instead of make-do solution...

i was unable to find a 0.5.10 version for sodium on 1.20.6 but the pull request above changes some files to allow nvidium to launch with 0.5.11 on 1.20.6.

**Comment by ShayBox** [comment]
0.2.9 needs back ported to 1.20.6
