### ISSUE TITLE
Visual Corruption on scaffolding blocks 

### ISSUE THREAD

**Issue by QPCrummer** [MCRcortex/nvidium#21]
![2023-05-10_17 07 13](https://github.com/MCRcortex/nvidium/assets/66036033/ac9c7cec-6995-4dc9-a537-e0880d51dd85)
![2023-05-10_17 07 31](https://github.com/MCRcortex/nvidium/assets/66036033/8e04f906-3f5f-498d-8b9f-bbc22f29a2dd)

After getting this corruption, I had this crash report. It seems like it sucked up all of the memory:
https://mclo.gs/P5XI1pj

If you need any more info, just ask!

It also does this on the sodium 0.4.10 release too

**Comment by Altirix** [comment]
can reproduce it, crashed my game too

same for cauldrons & fences or anything with a lot of faces id assume. i found the crash occurred at ~1069th Cauldrons & ~3464th for scaffolding in the same chunk

https://mclo.gs/Qtaoz1S

**Comment by MCRcortex** [comment]
Fixed in https://github.com/MCRcortex/nvidium/commit/40247d2050b68d11d5108083a2c0842efc2f367b
