### ISSUE TITLE
1.20.1 sodium 0.5.9/0.5.10/0.5.11

### ISSUE THREAD

**Issue by GrinlexGH** [MCRcortex/nvidium#213]
I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/releases) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)

**Comment by blankuserrr** [comment]
Thanks bbg

**Comment by korauo** [comment]
> I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/commit/b61a583f3caf57afc793fc013131b5f0c14819cd) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)

can u please make one for 1.20.6 too?

**Comment by DeimosHiver** [comment]
> I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/commit/b61a583f3caf57afc793fc013131b5f0c14819cd) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)

can you make it become a file? im new to github idk how to download it

**Comment by GrinlexGH** [comment]
> > I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/commit/b61a583f3caf57afc793fc013131b5f0c14819cd) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)
> 
> can u please make one for 1.20.6 too?

https://github.com/GrinlexGH/nvidium/releases/tag/1.20.6

**Comment by GrinlexGH** [comment]
> > I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/commit/b61a583f3caf57afc793fc013131b5f0c14819cd) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)
> 
> can you make it become a file? im new to github idk how to download it

![image](https://github.com/MCRcortex/nvidium/assets/77984877/ee62a0cd-5289-4d67-b905-aae23ae5d50a)

**Comment by korauo** [comment]
> > > I made a version which [compatible with sodium 0.5.11](https://github.com/GrinlexGH/nvidium/commit/b61a583f3caf57afc793fc013131b5f0c14819cd) and uploaded build in releases. I tested it and everything seems to be working well. All you need to do is retest it and release it to modrinth :)
> > 
> > 
> > can you make it become a file? im new to github idk how to download it
> 
> ![image](https://private-user-images.githubusercontent.com/77984877/345861223-ee62a0cd-5289-4d67-b905-aae23ae5d50a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTExNzMsIm5iZiI6MTcyMDE5MDg3MywicGF0aCI6Ii83Nzk4NDg3Ny8zNDU4NjEyMjMtZWU2MmEwY2QtNTI4OS00ZDY3LWI5MDUtYWFlMjNhZTVkNTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE0NDc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YTZiZjM5ZjgyYTM2ZTNlOWRlZDRkZDg5NjM4NDNhNWJkMmNiZTc0MTEzOGI2M2Q4MGJkODg2ODE5NTc3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.07UBnhQQJQ3CnVey1RRjh9qyqmFJbL4vEIEl01-E5i0)

thanks alot
