### ISSUE TITLE
Nvidiun not working

### ISSUE THREAD

**Issue by Rrrozker** [MCRcortex/nvidium#214]
Have an issue with this mod, it not working on 1.21 minecraft version, 0.5.11 Fabric, Graphic card Nvida gtx 1650 Ti
![Знімок екрана (1258)](https://github.com/MCRcortex/nvidium/assets/174821751/3cdb6d67-b3b9-4da8-8e89-cb0524eacaa6)
![image](https://github.com/MCRcortex/nvidium/assets/174821751/63d846b9-07d8-4a58-a38b-4acb3561d27e)

**Comment by Earthcomputer** [comment]
What makes you think Nvidium is not working? Is it the 60fps? Did you cap the fps at 60?

**Comment by Rrrozker** [comment]
> What makes you think Nvidium is not working? Is it the 60fps? Did you cap the fps at 60?

Render distance is low
