### ISSUE TITLE
nvidium not working :(

### ISSUE THREAD

**Issue by derpzisonthehub** [MCRcortex/nvidium#215]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Nvidium' (nvidium) 0.2.6-beta with any version that is compatible with:
		 - sodium 0.5.11+mc1.20.1
More details:
	 - Mod 'Nvidium' (nvidium) 0.2.6-beta requires version 0.5.7 or version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.11+mc1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

dawg I need nvidium for 1.20.1

**Comment by derpzisonthehub** [comment]
how do you close this I fixed this

**Comment by iy9k** [comment]
how do you fix this while staying on sodium 0.5.11

**Comment by MrCatlio** [comment]
> how do you fix this while staying on sodium 0.5.11

Theses are known to work currently for 1.20.1
Sodium: 0.5.7

**Comment by myusername450** [comment]
im experiencing the same thing
it told me to switch sodium to 0.5.8 but it created more issues where i have to remove nvidum completly to work
