### ISSUE TITLE
the game crashes when using nvidium

### ISSUE THREAD

**Issue by Kagayakazee** [MCRcortex/nvidium#216]
when adding the nvidium mod and when logging into any server, after a while the game crashes

version: 1.20.4
mods: https://imgur.com/a/pWxxFcH
logs: https://pastebin.com/raw/zwyvcjUk

**Comment by KarmaMarazu** [comment]
Pastebin link doesnt work incorrect permissions please reupload it to mclo.gs

**Comment by Kagayakazee** [comment]
new link: https://api.mclo.gs/1/raw/yFJG9qy

> Pastebin link doesnt work incorrect permissions please reupload it to mclo.gs

**Comment by KarmaMarazu** [comment]
https://mclo.gs/yFJG9qy this is not the crash log can you send the crash log instead

**Comment by MCRcortex** [comment]
Try using a launcher like prismlauncher or modrinth launcher not feather as feather has there own loader and changes which can break stuff

**Comment by Kagayakazee** [comment]
> https://mclo.gs/yFJG9qy это не журнал сбоев, можете ли вы вместо этого отправить журнал сбоев?

it doesn't show up in the "crash reporting" settings, the game just crashes

**Comment by Kagayakazee** [comment]
> Try using a launcher like prismlauncher or modrinth launcher not feather as feather has there own loader and changes which can break stuff

literally 3 days ago everything was working fine :(

**Comment by Earthcomputer** [comment]
This is not Nvidium's fault. Go to the Feather people for further support.
