### ISSUE TITLE
Nvidium do not work with sodium anymore

### ISSUE THREAD

**Issue by mrbluegame** [MCRcortex/nvidium#220]
for some reason minecraft just crash when ever I have the mods monds combined **I have tried installing both mods with different versions but it still crash**

Incompatible mods found!
Net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
     - Replace mod 'Nvidium' (nvidium) 0.2.6-beta with any version that is compatible with:
         - sodium 0.5.11+mc1.20.1
More details:
     - Mod 'Nvidium' (nvidium) 0.2.6-beta requires version 0.5.7 or version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.11+mc1.20.1!
    at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
    at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
    at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by KarmaMarazu** [comment]
https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2191775452
Add this to ur config folder and u should be done

**Comment by mrbluegame** [comment]
> [#204 (comment)](https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2191775452) Add this to ur config folder and u should be done

which file do I put it in my config folder? there is a lot of files

**Comment by KarmaMarazu** [comment]
> which file do I put it in my config folder? there is a lot of files
Just in the config folder not in a folder in the config folder

**Comment by mrbluegame** [comment]
> > which file do I put it in my config folder? there is a lot of files
> > Just in the config folder not in a folder in the config folder

it worked tysm

**Comment by Miniaudi** [comment]
which file do you have to put on the config folder?

**Comment by KarmaMarazu** [comment]
Nvidium is incompatible with sodium 6.x there is a 1.21.4 fork that should work use that or use sodium 5.x

**Comment by Miniaudi** [comment]
Im playing in 1.20.1 and i have Sodium 0.5.11

**Comment by KarmaMarazu** [comment]
The file libked in that comment

**Comment by Miniaudi** [comment]
What comment? i cant see any link

**Comment by Miniaudi** [comment]
oh nevermin i see it

**Comment by KarmaMarazu** [comment]
> [#204 (comment)](https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2191775452) Add this to ur config folder and u should be done

This

**Comment by Miniaudi** [comment]
Okay now what version of nvidium i install? the latest one?
