### ISSUE TITLE
Rendering issue with Nvidium 0.2.9-Beta

### ISSUE THREAD

**Issue by ghost** [MCRcortex/nvidium#221]
![image](https://github.com/user-attachments/assets/e477f4b4-fa8e-4401-ad01-dc783783f0af)
I have tried to use nvidium 0.2.9-beta with my GTX1650 however some rendering issues occured. I am not a minecraft mod nerd so i do not know how to fix this but i never had such any issue like this before with previous versions of this mod. I am assuming there may be a bug I am not sure. Help would be appreciated
Thanks!
Edit: I have just tested 0.2.8-beta and that also does not work

**Comment by frosthuuuund** [comment]
Post a seed or world if it isn't too large

**Comment by KarmaMarazu** [comment]
Oh no not this bug again

**Comment by ghost** [comment]
> Post a seed or world if it isn't too large

alr here is the seed (just to let you know i have tried many worlds and different 1.21 instances even and it still doesnt work.
seed: 153733092163157843

**Comment by ghost** [comment]
> Oh no not this bug again

i saw a similar issue to mine except that was when combined with another mod. Mine isnt. when running nvidium alone it is just like the screenshot i sent.

**Comment by KarmaMarazu** [comment]
> > Oh no not this bug again
> 
> i saw a similar issue to mine except that was when combined with another mod. Mine isnt. when running nvidium alone it is just like the screenshot i sent.

I remember when talking to cortex once she couldnt fix it before because she wasnt able to recreate the issue
Then i got on the hermitcraft s9 world and was able to recreate it till we _thought_ we fixed it sadly it looks like it came up again can you accurately recreate the issue on ur instance on ur own world?

**Comment by MCRcortex** [comment]
Does it work at all? or does it break at the same point every time, can you send an f3 please? is it any world aswell?

**Comment by frosthuuuund** [comment]
Have no issues with this world. Reproduce it with minimal setup on your machine.

https://files.catbox.moe/ofkb1x.png

**Comment by ghost** [comment]
> Does it work at all? or does it break at the same point every time, can you send an f3 please? is it any world aswell?

does not work at all. it also happens in servers and local saves.

**Comment by ghost** [comment]
> > > Oh no not this bug again
> > 
> > 
> > i saw a similar issue to mine except that was when combined with another mod. Mine isnt. when running nvidium alone it is just like the screenshot i sent.
> 
> I remember when talking to cortex once she couldnt fix it before because she wasnt able to recreate the issue Then i got on the hermitcraft s9 world and was able to recreate it till we _thought_ we fixed it sadly it looks like it came up again can you accurately recreate the issue on ur instance on ur own world?

not sure what you are asking me to do here?

**Comment by ghost** [comment]
> ![image](https://private-user-images.githubusercontent.com/111639659/348620580-e477f4b4-fa8e-4401-ad01-dc783783f0af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzA0NjQsIm5iZiI6MTcyMTAzMDE2NCwicGF0aCI6Ii8xMTE2Mzk2NTkvMzQ4NjIwNTgwLWU0NzdmNGI0LWZhOGUtNDQwMS1hZDAxLWRjNzgzNzgzZjBhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzU2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDA3ZmQzYTlhMDEzNzAzMTI3YTNjMWQzZjFlMzE0NzIyNGZmZDFkODgzZDQzNjFhNWViNWFmODgwOTlhNTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kdoYx_n0ViEXTEx1K0nKAaQp8CK-wqRN8zlZBlE8Ciw) I have tried to use nvidium 0.2.9-beta with my GTX1650 however some rendering issues occured. I am not a minecraft mod nerd so i do not know how to fix this but i never had such any issue like this before with previous versions of this mod. I am assuming there may be a bug I am not sure. Help would be appreciated Thanks! Edit: I have just tested 0.2.8-beta and that also does not work

I forgot to mention that I do have an i5-6500. not sure how this will affect it in anyway

**Comment by ghost** [comment]
I might just not use nvidium at all till it is patched for gtx 16 series idk

**Comment by MCRcortex** [comment]
> Does it work at all? or does it break at the same point every time, can you send an f3 please? is it any world aswell?

can you send an f3 screenshot please

**Comment by ghost** [comment]
> > Does it work at all? or does it break at the same point every time, can you send an f3 please? is it any world aswell?
> 
> can you send an f3 screenshot please

let me download the nvidium again

**Comment by ghost** [comment]
also i forgot to mention that i am installing nvidium alongside a modpack made in the modrinth community.

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/25ddb5b3-c782-472a-9b91-a406e24fb871)
this is before nvidium (no other mods are installed). f3 on and just fabric loader.

**Comment by ghost** [comment]
> ![image](https://private-user-images.githubusercontent.com/111639659/348653030-25ddb5b3-c782-472a-9b91-a406e24fb871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzUxMTAsIm5iZiI6MTcyMTAzNDgxMCwicGF0aCI6Ii8xMTE2Mzk2NTkvMzQ4NjUzMDMwLTI1ZGRiNWIzLWM3ODItNDcyYS05YjkxLWE0MDZlMjRmYjg3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwOTEzMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTg4YTUwNTk1NDgxMjMyYTE0YzQzZmVlMGZkMjZlM2YwMzdkMTRkNTYyYTNiNTA0MWNiZGZmOGQyMmM0YWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1BdgDiowaU6osAh-dS4jhfMsg76OcgPVhAHuehGYzR8) this is before nvidium (no other mods are installed). f3 on and just fabric loader.

default settings just changed fov to 90 and gui scale to 2

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/c9022ce8-a474-485a-800a-d95bd947e599)
this is after nvidium and sodium (only those 2 nothing else) on a fresh instance.

**Comment by ghost** [comment]
this is a new world just to show its the same all through out. 6039803103558490277

**Comment by MCRcortex** [comment]
Update your graphics drivers

**Comment by ghost** [comment]
> Update your graphics drivers
oh yeah. i decided to use the initial release drivers for all my pc components. lol

**Comment by ghost** [comment]
ok i might aswell update everything then. give me 30-45 min

**Comment by ghost** [comment]
> Update your graphics drivers

ty so much. updating my drivers did work after all lol
