### ISSUE TITLE
Some chunks forces themselves to be unloaded for some reason 1.21

### ISSUE THREAD

**Issue by makumaku1974** [MCRcortex/nvidium#222]
![image](https://github.com/user-attachments/assets/29eaf532-f0c1-4d3f-a279-fe651b7f6d30)

**Comment by MrCatlio** [comment]
try to check to see if another mod is possibly causing the chunks to be unloaded

**Comment by makumaku1974** [comment]
i have immediately fast on

**Comment by makumaku1974** [comment]
![image](https://github.com/user-attachments/assets/2de742c8-cb1a-419f-b2cb-2c4eb00d79eb)

This also happens when im too far.

**Comment by KarmaMarazu** [comment]
Ur running out of vram lower ur RD

**Comment by makumaku1974** [comment]
> Ur running out of vram lower ur RD

the nvidium's render distance got it.

**Comment by purple-emily** [comment]
I know this is a closed issue, but can this be added to the README and/or mod pages under FAQ?

The glitching out chunks is an issue I have been having and I had to dig my way to this post to understand it was the VRAM running out. A log entry in the Minecraft console might be helpful as well?

**Comment by purple-emily** [comment]
@makumaku1974 -- just in case closed issues don't show notifications

**Comment by purple-emily** [comment]
@MCRcortex Hopefully not a difficult job but might stop some issues being opened in the future
