### ISSUE TITLE
What requirements am I missing here?

### ISSUE THREAD

**Issue by Tanjiraaaaa** [MCRcortex/nvidium#224]
https://pastes.dev/xjYm7d7WkM

**Comment by Tanjiraaaaa** [comment]
![image](https://github.com/user-attachments/assets/fd248068-5e1b-44a1-98eb-09c97352380c)

**Comment by TH3N3WN00B** [comment]
This one
![image](https://github.com/user-attachments/assets/c7438fe2-0180-4e1f-b11d-c4e70af7c275)

**Comment by SpyC0der77** [comment]
LOL

**Comment by TH3N3WN00B** [comment]
@MCRcortex pls close this

**Comment by KarmaMarazu** [comment]
Ill close it for ya
