### ISSUE TITLE
1.19.4 crash on spawn when camera move fast

### ISSUE THREAD

**Issue by KalitkaS** [MCRcortex/nvidium#227]
On server spawn, when turning the camera, a crash occurs due to incorrect memory allocation by the mod. Manipulating video memory and memory in the launcher had no effect.
32gb RAM.
Server test: mc.diamondworld.pro
Other mods are not related to this, because... there was testing with and without them.
[tl-logger550772924659038173.txt](https://github.com/user-attachments/files/16426598/tl-logger550772924659038173.txt)
logs

**Comment by KalitkaS** [comment]
Please write if you encounter this problem, I tested it on different PCs and also found this error. Please advise a solution, my game sometimes crashes and I found a way how to call them to get a guaranteed failure.
Windows 11, 13600kf, 4070ti/super, 32gb ddr5

**Comment by KarmaMarazu** [comment]
1.19.4 isnt being updated anymore as well as legacy launcher is a cracked launcher we cant know what it breaks there for we cant help you fix this

Also dont go to the discord posting ur issue here and trying to ping EVERYONE bit rude ngl

**Comment by KalitkaS** [comment]
[tl-logger550772924659038173.txt](https://github.com/user-attachments/files/16426586/tl-logger550772924659038173.txt)
