### ISSUE TITLE
weird crash on 1.21

### ISSUE THREAD

**Issue by makyuplier** [MCRcortex/nvidium#229]
hallo i really love this mod but when i updated my world from 1.20.1 to 1.21 it crashes for some reason. i run a 3060 and my driver is 546.33 (might be relevant since whenever i crash it keeps telling me it might be a driver issue). i tried turning of other settings of the mod even disabling the keep distance but it still crashes. 
![bug](https://github.com/user-attachments/assets/1e0307a8-bc6a-4c2e-b906-cd06d03b5f98)
![mods](https://github.com/user-attachments/assets/f5fca51f-9a42-4511-a3f1-3a37cb34a925)

**Comment by KarmaMarazu** [comment]
I recommend updating ur drivers we cant help much more with this without logs but either way i recommend updating them if it still happens after updating them please send ur crash logs through a website called mclo.gs

**Comment by makyuplier** [comment]
where does one find the crash logs? i tried finding them in crash-reports but i cant find the one that i just tested. does uploading my latest log help?

**Comment by MCRcortex** [comment]
That is fine, thank you <3

**Comment by makyuplier** [comment]
https://api.mclo.gs/1/raw/7w7Wjot
i hope this helps, if not ill send the last crash report which im pretty sure was caused by nvidium. thanks :>

**Comment by MCRcortex** [comment]
Can you please update your graphics drivers

**Comment by makyuplier** [comment]
ok lemme try and see if it crashes after reinstall brb

**Comment by MCRcortex** [comment]
Download from the nvidia website directly
https://www.nvidia.com/download/index.aspx

**Comment by makyuplier** [comment]
hallo i reinstalled my drivers to 560.70 using nvcleaninstall (didnt see your comment sorry) and has not crashed after so i think it might be fixed after that, probably should have done that in the first place anw. ill come back here if it crashes again. thanks for the help! 
(also logs after the reinstall)
https://api.mclo.gs/1/raw/7Z7568n

**Comment by MCRcortex** [comment]
Np glad it fixed it!
