### ISSUE TITLE
Add support for sodium 5.9/5.10. for 1.20.1 fabric

### ISSUE THREAD

**Issue by TheShadyyOneYT** [MCRcortex/nvidium#231]
I would love to use this mod for more recent versions of sodium because of indium updates and sodium updates are more recent, and it would be lovely to use a higher version of sodium if this can be updated. I see you currently have completed 0.5.7/.8, but 0.5.9 would be be lovely at the very least. (I don't know how to change the flair, or if I can)

**Comment by TheShadyyOneYT** [comment]
nvm i realized you updated it, ignore this

**Comment by KarmaMarazu** [comment]
https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2191775452
