### ISSUE TITLE
extreme lag at high render distance

### ISSUE THREAD

**Issue by BigBoyCarl29** [MCRcortex/nvidium#232]
am having extreme lag when loading chunks new or already visited. i also have bobby mod installed, i think that might be the issue.
![2024-08-04_16 23 00](https://github.com/user-attachments/assets/21f0d553-edac-47c4-8c4f-10c829ebacf1)

**Comment by MCRcortex** [comment]
you have 2 gb of ram allocated with 128 rd chunks loaded, allocate more ram, not nvidiums fault directly
