### ISSUE TITLE
Incompatible with Sodium

### ISSUE THREAD

**Issue by Mortycio** [MCRcortex/nvidium#236]
![image](https://github.com/user-attachments/assets/4cebbfec-1ab6-4129-84be-f1d1216f9572)

As described in the screenshot, version 0.2.6-beta of the Nvidium mod is incompatible with version 0.5.11 of the 'Sodium' mod. The proposed solution cannot be applied because it would lead to a series of other incompatibilities with the remaining and numerous mods that require Sodium 0.5.11.

minecraft version: 1.20.1
fabric loader: 0.16.0
java version: 17.0.12

**Comment by KarmaMarazu** [comment]
https://github.com/MCRcortex/nvidium/issues/204#issuecomment-2191775452
