### ISSUE TITLE
Add support for 1.19.2 (very many modpacks)

### ISSUE THREAD

**Issue by JustRomanBZK** [MCRcortex/nvidium#238]
There are so many builds running now, on 1.19.2 and Nvidium could allow people with shaders to play.

**Comment by Felix14-v2** [comment]
> Nvidium could allow people with shaders to play

Each shader pack must be rewritten to work with it even if Nvidium provides shaders support.

**Comment by KarmaMarazu** [comment]
> could allow people with shaders to play.

nvidium doesnt work with shaders
and sodium 5.8 (or above) must be back ported to 1.19.2 to work

**Comment by JustRomanBZK** [comment]
> > could allow people with shaders to play.
> 
> nvidium doesnt work with shaders and sodium 5.8 (or above) must be back ported to 1.19.2 to work

You can take an alpha that has been running since 1.19.4 and only have to change a few things.

**Comment by CoolAid48** [comment]
> You can take an alpha that has been running since 1.19.4 and only have to change a few things.

You'd have to change a lot more than "a few things" for what you're requesting to work.
