### ISSUE TITLE
Sodium incompatability

### ISSUE THREAD

**Issue by ZoenkBoenk** [MCRcortex/nvidium#239]
So sodium released a new version which is incompatible with nvidium, it isnt really incompatible it works with sodium, but the nvidium settings tab doesn't show up in the sodium settings menu. Could y'all fix that?? :3

thx

**Comment by KarmaMarazu** [comment]
dont expect nvidium to work for a while on 0.6 also its still in beta some things might still change before the full release of 0.6

**Comment by rakantoh** [comment]
nvidium 0.2.7 for mc 1.20.6 is incompatible with sodium 0.5.11, fix please.

**Comment by Samalando** [comment]
Put [this](https://cdn.discordapp.com/attachments/1252682736817147935/1253095976256934008/fabric_loader_dependencies.json?ex=66d38812&is=66d23692&hm=f5a9322a06dedf98af35bdbb008291d274fa76c1566c3cd0033a77d1e7de9219&) that into your config folder

**Comment by rakantoh** [comment]
the file is no longer available, but i change the mod support version in the json, simply adding ">", now mc 1.20.6 start with nvidium normally.
For 1.21 and sodium 0.6.0, not support yet, right?

**Comment by KarmaMarazu** [comment]
> For 1.21 and sodium 0.6.0, not support yet, right?

as said before dont expect it for a while 

and for the first thing look at the closed pinned issue at the top talking about this
