### ISSUE TITLE
NVIDIUM causing other applications to lag

### ISSUE THREAD

**Issue by wjpgit-vuw** [MCRcortex/nvidium#240]
Heya,

Loving the use of nvidium, just started using it. However, I've noticed that when it's enabled, other applications such as YouTube in full screen (while minecraft is also in full screen on another monitor) causes YouTube to run at about 2 frames per second. As soon as I disable Nvidium OR put minecraft into window mode, it runs smoothly again. Is this because Nvidium is causing my RTX 3060ti to solely focus majority of its power on minecraft?

**Comment by KarmaMarazu** [comment]
You can try limiting the vram usage of nvidium that might help a bit?

**Comment by MCRcortex** [comment]
when in fullscreen, windows will prioritize that application and since nvidium uses _alot_ of the gpu resources, id suspect its just bottlenecking, id suggest enabling vsync or limiting fps.

**Comment by wjpgit-vuw** [comment]
> when in fullscreen, windows will prioritize that application and since nvidium uses _alot_ of the gpu resources, id suspect its just bottlenecking, id suggest enabling vsync or limiting fps.

Capping fps to 240 fixed it. Silly mistake, thank you!

**Comment by MCRcortex** [comment]
np! happy it was an easy fix
