### ISSUE TITLE
i cant use nvidium whit sodium 6.0 :(

### ISSUE THREAD

**Issue by WhitefangY** [MCRcortex/nvidium#243]
help

**Comment by TH3N3WN00B** [comment]
The best thing you can get is Sodium 5.11 working with this one https://discord.com/channels/973046939375505408/1267808822768963625/1275256515833368587

**Comment by WhitefangY** [comment]
that doesnt work whit most mods i have

**Comment by CoolAid48** [comment]
Nvidium doesn't work with Sodium 0.6. Don't expect it to work for a while, at least until Sodium 0.6 is out of beta.

**Comment by WhitefangY** [comment]
sadly i cant us it then :(
