### ISSUE TITLE
[1.20.1] [0.3.1] Crash at startup 

### ISSUE THREAD

**Issue by MihanDeNoob** [MCRcortex/nvidium#247]
"Suspected Mods: java.lang.UnsupportedClassVersionError: net/minecraft/class_1041 has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0" 

Seems to be java version issue? If its so, can i use new version of java on 1.20.1 or im going to have issues with mods? 

Crashlog: https://mclo.gs/k8ig938

**Comment by Philanche** [comment]
Nvidium 0.3.1 is for minecraft 1.21.x

**Comment by KarmaMarazu** [comment]
3.1 is for 1.21 and 1.21.1

**Comment by MihanDeNoob** [comment]
> 3.1 is for 1.21 and 1.21.1

oh so fabric_loader_dependencies.json fix doesnt work? Is there any plans for backport or its not possible? 
After all, 1.20.1 is the core version of minecraft currently. 

Also, did i misunderstood the fabric_loader_dependencies.json fix in the first place? xd

**Comment by Quantum39** [comment]
no changing JSON is for another fix

**Comment by MihanDeNoob** [comment]
> no changing JSON is for another fix

Thx!
