### ISSUE TITLE
[SUGGESTION] Port on 1.19.2

### ISSUE THREAD

**Issue by ENC4YP7ED** [MCRcortex/nvidium#25]
Most People play Mods / Modpacks  on Fabric 1.19.2 and can't enjoy nvidium so It would be great to see a port to 1.19.2

**Comment by ShibeTemple** [comment]
This would be great :)

**Comment by mateus3c** [comment]
i agree, it would be amazing to have nvidium on 1.19.2

**Comment by duakc** [comment]
1.18.2 This mod is also required

**Comment by Beerandoo** [comment]
yes, a lot of people play fabric mods on 1.19.2 i think its the most supported modded minecraft version for fabric atleast if i'm not mistaken.

I really want them to release this mod on 1.19.2 as it is the version of minecraft i play fabric on the MOST!

**Comment by elpideus** [comment]
Modpack creator here. I would really love to see the mod backported for 1.19.2, as there are a lot of opportunities. This mod could be a life saver on heavy modded instances.

**Comment by ZlordHUN** [comment]
+1

**Comment by TheElevatedOne** [comment]
This would be amazing, even if it was a port of one version and then never touched, it would still be used a lot.

**Comment by MCRcortex** [comment]
Sorry the sodium pipeline is very different in older versions and cannot support async bfs easily
