### ISSUE TITLE
Support for M3 Apple Silicon

### ISSUE THREAD

**Issue by csutora** [MCRcortex/nvidium#252]
hi!

Apple Silicon supports mesh shaders in hardware since version M3, so it would be nice if the mod could support that platform as well.

some pitfalls could be:
- mesh shaders are not performant enough on M3 compared to nvidia
- the mod depends on something else other than pure mesh shaders
- render code is not easily ported over and/or you don't want to, in which case I'd love to help and put in hours for this to happen.

please consider it.
have a good one!

**Comment by AlexanderwithaA** [comment]
This likely won’t be possible, the mesh shader support is in metal, just like nvidia did with its mesh shaders extension to the opengl library apple would have to do the same and considering that apple stopped opengl support at 4.1 that doesn’t seem likely.

**Comment by csutora** [comment]
as far as i'm aware metal is already being used on macos behind the scenes to translate opengl calls.

**Comment by Felix14-v2** [comment]
> as far as i'm aware metal is already being used on macos behind the scenes to translate opengl calls.

Only limited set of calls. I don't believe that Apple would work on this. But you can request adding support for OpenGL mesh shaders to the Asahi Linux driver — it already has better OpenGL support (OpenGL 4.6) than Apple (software emulation of OpenGL 4.1). This may work since AMD's new driver with OpenGL Mesh Shaders have almost been released, and this may become a kind of trend.

**Comment by csutora** [comment]
good idea! in case of them adding support to their drivers, would the mod work on Asahi Linux with minimal changes?

**Comment by Felix14-v2** [comment]
I think yes, but I'm not the mod dev, so wait for a word from Cortex

**Comment by wahfl2** [comment]
That is, if it supports specifically `GL_NV_MESH_SHADER`. Other extensions would possibly require significant changes.

**Comment by CrabbyDisk** [comment]
> > as far as i'm aware metal is already being used on macos behind the scenes to translate opengl calls.
> 
> Only limited set of calls. I don't believe that Apple would work on this. But you can request adding support for OpenGL mesh shaders to the Asahi Linux driver — it already has better OpenGL support (OpenGL 4.6) than Apple (software emulation of OpenGL 4.1). This may work since AMD's new driver with OpenGL Mesh Shaders have almost been released, and this may become a kind of trend.

for real?
