### ISSUE TITLE
Nvidium requesting sodium version 0.5.7(8) and not 0.5.11 | quilt 1.20.1

### ISSUE THREAD

**Issue by akustom** [MCRcortex/nvidium#259]
i know about the fabric_loader_dependencies thing; it works amazing on fabric, but im using quilt and not fabric this time. can anyone help fix this issue?

**Comment by KarmaMarazu** [comment]
Quilt has its own overwrite (idk how so cant help u with that) u can look into how they overwite dependencies. Another solution is to use fabric or use the older sodium version for now and downgrade the other mods too

**Comment by akustom** [comment]
oh right, thx. i did what you said, took a while to understand how to override it, since their way is quite different, but i managed to got it working. thx again

**Comment by KarmaMarazu** [comment]
> since their way is quite different, but i managed to got it working. thx again

out of interest mind sharing how you did the overwrite i looked at it a while ago but couldnt figure it out im interested to see what went wrong back then

**Comment by akustom** [comment]
> > since their way is quite different, but i managed to got it working. thx again
> 
> out of interest mind sharing how you did the overwrite i looked at it a while ago but couldnt figure it out im interested to see what went wrong back then

sorry for the extremely late reply but, here's the json i used. it took me a while to get it working since im very new to this, so i only had the wiki and git for reference
[quilt-loader-overrides.json](https://github.com/user-attachments/files/17531900/quilt-loader-overrides.json)
