### ISSUE TITLE
Crashes when Iris 1.6.3 (w sodium) installed

### ISSUE THREAD

**Issue by RealmKebab** [MCRcortex/nvidium#26]
![image](https://github.com/MCRcortex/nvidium/assets/73048123/7432c07f-4b67-4e41-9ff6-64edc15adcd6)

**Comment by Taiyou06** [comment]
currently iris is not supported.

**Comment by RealmKebab** [comment]
When is it going to be supported?

**Comment by Taiyou06** [comment]
there's no ETA.

**Comment by RealmKebab** [comment]
Oh alright, I'll close it as it's kind a dupe of #3
