### ISSUE TITLE
[Question] Is this usable in a multiplayer scenario with different GPU vendors?

### ISSUE THREAD

**Issue by DarthCaesium** [MCRcortex/nvidium#260]
Hi! Sorry, the title isn't very good, but this is a highly specific case and the title would've been excessively long otherwise. Anyway, I have an AMD iGPU (thus this mod is incompatible on my end, and so the mod will disable itself on my machine due to this), but my friend has an Nvidia GTX 1660, which has mesh shader support. If I'm hosting a server with it, will my friend be able to benefit from Nvidium, or would this cause a client desync and/or crash?

**Comment by Philanche** [comment]
This is a purely client-side mod, so they can use it on their client even if you don't (and in fact, you can't even use nvidium *on* a server, as it only affects rendering)

**Comment by DarthCaesium** [comment]
Thanks! The quick reply was very appreciated as well.
