### ISSUE TITLE
Update to 1.21.3

### ISSUE THREAD

**Issue by NiaSwift** [MCRcortex/nvidium#266]
Please? Pretty please? Pretty please with a cherry on top? (Take your time tho ❤️)

**Comment by Earthcomputer** [comment]
How many duplicates of the same issue do we need?

**Comment by NiaSwift** [comment]
> How many duplicates of the same issue do we need?

I looked in the "Open Issues" tab before I made my issue, and saw there weren't any about this topic so I made one. I also checked now in the "Closed Issues" tab, and granted, there is one, but it was closed by the user who made it.

Also, your passive-aggressiveness is uncalled for. Even if there was an issue made about this that was still open before I made mine and I hadn't noticed it, your being mean is just that: Mean. Unnecessarily so.
