### ISSUE TITLE
don't work with iris

### ISSUE THREAD

**Issue by Alexander020304** [MCRcortex/nvidium#3]
not sure if this is on purpose  but nvidium is not compatible with iris 1.6.1

**Comment by Earthcomputer** [comment]
At present, this is expected, as it would take a significant amount more work to get it to work with Iris.

**Comment by Alexander020304** [comment]
understandable ; just wanted confirmation. what is currently conflicting with iris?

**Comment by MCRcortex** [comment]
The fundamental way this mod works is different to iris, fixing it is very hard and complex, let alone fixing it correctly, perhaps in the future a middle ground can be developed and some support added, however that is not for the foreseeable future

**Comment by Owehttamy** [comment]
> The fundamental way this mod works is different to iris, fixing it is very hard and complex, let alone fixing it correctly, perhaps in the future a middle ground can be developed and some support added, however that is not for the foreseeable future

I've seen the devs of Distant Horizons talk about how they could manage compatibility with Iris some while ago. So, even if their mod is drastically different in many ways, it might be helpful to ask them alongside IMS if you ever reach a point where you want to try figuring out shaders as some other pointers of where even to start.

**Comment by PFnove** [comment]
it would be nice to have some sort of builtin antialiasing since this doesn't work with iris (no antialiasing shaders) and the staircase diagonal lines are really noticeable

**Comment by memphismc** [comment]
so from what i understand, this is pretty much never getting shader support?

**Comment by Vricken** [comment]
> it would be nice to have some sort of builtin antialiasing since this doesn't work with iris (no antialiasing shaders) and the staircase diagonal lines are really noticeable

just use Nvidia control pannel application settings to get AA

**Comment by TimPGamer** [comment]
I dont know much about shaders and stuff, but may it be possible to like implement a custom shader engine, with only support for certain shaders, that support it? IDK how difficult i would be, but if possible, u could at least try it.

**Comment by WinsomeGuy** [comment]
If this mod somehow manage shaders, It will surely explode.

**Comment by frak0d** [comment]
> > it would be nice to have some sort of builtin antialiasing since this doesn't work with iris (no antialiasing shaders) and the staircase diagonal lines are really noticeable
> 
> just use Nvidia control pannel application settings to get AA

linux version of nvidia control panel doesn't have any graphics options, so it would be better to have option in the mod itself

**Comment by sleeplessKomodo** [comment]
imo, I don't see the point of this mod if you can't use shaders. If you have an NVIDIA GPU, with sodium you'll get more than enough frames on basically any machine. 

I understand there's complexity involved, and I'm not a programmer, but can someone explain why anyone might need 500+ fps?

**Comment by KarmaMarazu** [comment]
> I understand there's complexity involved, and I'm not a programmer, but can someone explain why anyone might need 500+ fps?
further render distance

**Comment by Philanche** [comment]
> imo, I don't see the point of this mod if you can't use shaders. If you have an NVIDIA GPU, with sodium you'll get more than enough frames on basically any machine.
> 
> I understand there's complexity involved, and I'm not a programmer, but can someone explain why anyone might need 500+ fps?

Well, there's the fact that it works with lower end cards which might not get enough frames, especially not when running shaders on top, and also many people don't necessarily want or need shaders all the time. If you don't want to use the mod, no one is forcing you to, but clearly there is a point to this mod, otherwise there wouldn't be over 3 million downloads. As Marazu said, this mod also helps a lot with higher render distances, and can also allow people to run heavier mods and counteract their impact.

**Comment by Felix14-v2** [comment]
> I don't see the point of this mod if you can't use shaders

Another mod by Cortex, Voxy, _kinda_ works with some tweaked shaders. Voxy also supports mesh shaders and allows you to play with an insane render distance (hundreds and thousands of chinks) thanks to the LOD approach.

**Comment by Alexander020304** [comment]
With the Aperture in development this should be revisited. to try to add compatibility out of the box

**Comment by Felix14-v2** [comment]
> With the Aperture in development this should be revisited. to try to add compatibility out of the box

That's something that must be done on Aperture's side. So, you should ask IMS about this.
