### ISSUE TITLE
Add Iris support

### ISSUE THREAD

**Issue by Pfostierer** [MCRcortex/nvidium#32]
This kind of a mod, specifically for enhancing performance and gaining a ton of it, would make shaders run butter smooth.

**Comment by TailOrTaily** [comment]
i'd love to have iris support having no shaders is the only thing stopping me from using this on minecraft really i do only use it with vivecraft and there it runs beyond fantastic it's the best fps mod i seen

**Comment by McJeff201** [comment]
Yes please! Hoping this comes soon

**Comment by Un1q32** [comment]
iris will not come in the near future, sorry, unless the dev changes their mind.

**Comment by canthisbe** [comment]
If iris shaders with nvidium isn't possible, can it be made compatible by disabling itself when shaders are turned on?

**Comment by luigi052005** [comment]
> If iris shaders with nvidium isn't possible, can it be made compatible by disabling itself when shaders are turned on?

Good idea.

**Comment by SyberiaK** [comment]
> If iris shaders with nvidium isn't possible, can it be made compatible by disabling itself when shaders are turned on?

As I see, this was added in 0.1.14 👏

**Comment by Riyuukii** [comment]
any updates regarding using nvidium with shaders on?

**Comment by NinoDLC** [comment]
Can't have performance AND prettiness in Minecraft it seems :(

**Comment by https-biagio** [comment]
It's actually iris that should add support for nvidium.

**Comment by GibrielS** [comment]
https://github.com/IrisShaders/Iris/issues/2320

**Comment by GibrielS** [comment]
Iris is not planning this either so it is dead.
