### ISSUE TITLE
Map loading problem + minecraft crash

### ISSUE THREAD

**Issue by 1stDRAGONAMSTER** [MCRcortex/nvidium#34]
As soon as the Vram of my 3070 is filled to 7.5/8 GB, the PC starts writing the data to another memory of the GPU and shortly after that the world stops loading and crashes.
On the picture you can see the crash on the graphics and you can also see roughly how much memory was used.
![Task-Manager_Minecraft-Absturz](https://github.com/MCRcortex/nvidium/assets/135706228/a5e8afe0-7277-41ec-8a49-fc454bd6fef0)

**Comment by MCRcortex** [comment]
There is a config called "Max gpu memory" you should set this to probably around 6000-7000, it will stop the program from using all your vram and crashing
