### ISSUE TITLE
Could you please update the version 1.12.2

### ISSUE THREAD

**Issue by kefeng241** [MCRcortex/nvidium#37]
We want version 1.12.2 of the mod，we can pay something for it

**Comment by diarm56** [comment]
Short answer NO.
longer Answer: Nvidium is an alpha mods still in early developpement there are no planed compatibility for other minecraft version than the latest relaese.
and Nvidium requiere sodium 0.4.10 wich doesnt exist for 1.12.2. (no version of sodium exist for this version)

**Comment by Felix14-v2** [comment]
> We want version 1.12.2 of the mod

You can use [Nothirium](https://github.com/Meldexun/Nothirium) as a Sodium alternative. Anyway, what's the reason of playing on older versions? Especially an ancient 1.12.2

**Comment by ghost** [comment]
> > We want version 1.12.2 of the mod
> 
> You can use [Nothirium](https://github.com/Meldexun/Nothirium) as a Sodium alternative. Anyway, what's the reason of playing on older versions? Especially an ancient 1.12.2

although I think the new versions are better and play them

but on 1 12 2 you can make a server with plugins and mods

and factories still do not have normal plugin support

mods that replace plugins are very truncated and there are few of them
cardboard is dead

and the same Industrial Craft 2 Experimental is still not available on 1 19 4

**Comment by luigi052005** [comment]
> > > We want version 1.12.2 of the mod
> > 
> > 
> > You can use [Nothirium](https://github.com/Meldexun/Nothirium) as a Sodium alternative. Anyway, what's the reason of playing on older versions? Especially an ancient 1.12.2
> 
> although I think the new versions are better and play them
> 
> but on 1 12 2 you can make a server with plugins and mods
> 
> and factories still do not have normal plugin support
> 
> mods that replace plugins are very truncated and there are few of them cardboard is dead
> 
> and the same Industrial Craft 2 Experimental is still not available on 1 19 4

What are you trying to say?

**Comment by ghost** [comment]
> > > > We want version 1.12.2 of the mod
> > > 
> > > 
> > > You can use [Nothirium](https://github.com/Meldexun/Nothirium) as a Sodium alternative. Anyway, what's the reason of playing on older versions? Especially an ancient 1.12.2
> > 
> > 
> > although I think the new versions are better and play them
> > but on 1 12 2 you can make a server with plugins and mods
> > and factories still do not have normal plugin support
> > mods that replace plugins are very truncated and there are few of them cardboard is dead
> > and the same Industrial Craft 2 Experimental is still not available on 1 19 4
> 
> What are you trying to say?

the fact that the old version does not mean bad even if the forge developers think so
