### ISSUE TITLE
Boats not getting rendered on multiplayer

### ISSUE THREAD

**Issue by adabugra** [MCRcortex/nvidium#39]
If you load a chunk with boats that players or entitys are on they are going invisible until pressing f3+a.
![image](https://github.com/MCRcortex/nvidium/assets/57899270/406c438a-34a9-48b6-ae6c-cfcaef22dd73)
![image](https://github.com/MCRcortex/nvidium/assets/57899270/a3c2ff52-d3cd-4528-b37f-2e03d95313ce)

**Comment by MCRcortex** [comment]
does this issue still happen with 0.1.15 if so can you please upload a log?
