### ISSUE TITLE
parts of the world momentarily stop rendering when crossing chunk borders

### ISSUE THREAD

**Issue by The-Nyla** [MCRcortex/nvidium#4]
this issue doesn't seem to affect gameplay at all, as it only happens for a few frames when crossing chunk borders, and isn't very noticeable most of the time, but when crossing chunk borders sometimes section of the world will stop rendering for a few frames, which can be annoying, but isn't a huge issue.

**Comment by The-Nyla** [comment]
took a while but I got a screenshot of an instance of it happening:
![image](https://user-images.githubusercontent.com/79489385/233191596-7fb22988-37bc-421b-bdd9-6395d4aba184.png)

I also found another instance where liquids and block entities appeared to render through the ground and the section of the world affected was tinted bright white, this also occurred while standing on a chunk border, however any attempt to take a screenshot (in minecraft or out of minecraft) failed, as starting to take a screenshot from windows, or taking a screenshot with F2, appeared to temporarily fix the rendering issue, I have no idea why, but I assume it's because of how the mod works with the GPU.

**Comment by MCRcortex** [comment]
Fixed in https://github.com/MCRcortex/nvidium/commit/52b1e5d6ca8004f4284d7b3af579c2f3d0af9326
