### ISSUE TITLE
port for AMD 

### ISSUE THREAD

**Issue by lukim007** [MCRcortex/nvidium#41]
can you pls in the future make a port for AMD

**Comment by ghost** [comment]
nvidium is the first to use nvidia opengle technologies

therefore, it is unlikely that this is possible on amd, but I probably don’t know something

**Comment by CrabbyDisk** [comment]
Appearantly AMD gpus support mesh shaders wich is what nvidium uses. This could be possible.

**Comment by Inconn** [comment]
i believe to support other gpus it would require vulkan, since mesh shaders on other gpus are only available on vulkan.
on opengl, only nvidia mesh shaders are supported.

**Comment by MCRcortex** [comment]
Would not do it in this mod if i did such a thing sorry, yea you are correct, vk mesh shaders do exist but its different from the nv extension

**Comment by nonetrix** [comment]
I don't expect this to ever be ported, but could a AMD equivalent be made? Surely there are some AMD specific OpenGL extensions that could boost performance greatly as well, maybe someone else could work on this perhaps I would like to see it. I'm just throwing this out as a suggestion, so maybe someone picks it up

I found this list that might be of use, doesn't seem as extensive as the NVIDIA one so maybe AMD sticks more to standards. Still might be some gains to be made perhaps, I don't know much about graphics programming 
https://registry.khronos.org/OpenGL/extensions/AMD/

**Comment by Funtimes909** [comment]
Hey, I'd love to see an AMD version of this mod using AMD specific OpenGL extensions too, unfortunately I know little to nothing about graphics programming myself however it is possible to convert OpenGL programs to vulkan using drivers such as zink
https://www.khronos.org/assets/uploads/developers/presentations/Vulkan-09-Zink-OpenGL-on-Vulkan-SIGGRAPH-Jul19.pdf
However I also understand if you do not want to work on an AMD port if this mod is tiring enough 😅

**Comment by Andarwinux** [comment]
Zink won't magically increase fps, but it could theoretically be used as an interop bridge to provide VulkanMod with compatibility with legacy OpenGL mods.

**Comment by nonetrix** [comment]
> Zink won't magically increase fps, but it could theoretically be used as an interop bridge to provide VulkanMod with compatibility with legacy OpenGL mods.

In some cases it actually does, but this seems to be the exception rather than the rule. I wouldn't know if Minecraft if one of these edge cases. However, no mod is needed for Zink itself, to my understanding any OpenGL program should be able to use it provided theirs no issues

**Comment by Andarwinux** [comment]
Zink itself is straightforward to use, but it's almost impossible to get a performance boost unless the IHV only provides inferior native OpenGL drivers and also provides quality Vulkan drivers, which is not the case for Windows desktop devices. IHVs that have a quality Vulkan driver also offer a quality OpenGL driver, and IHVs that only have an inferior OpenGL driver won't offer a quality Vulkan driver to give you high performance with Zink. The only way to potentially bring performance gains is to use native Vulkan rendering like  VulkanMod, and then use Zink for VK<->GL interop to provide compatibility with legacy mods, like [X-Plane](https://www.supergoodcode.com/do-not/).

**Comment by nonetrix** [comment]
> Zink itself is straightforward to use, but it's almost impossible to get a performance boost unless the IHV only provides inferior native OpenGL drivers and also provides quality Vulkan drivers, which is not the case for Windows desktop devices. IHVs that have a quality Vulkan driver also offer a quality OpenGL driver, and IHVs that only have an inferior OpenGL driver won't offer a quality Vulkan driver to give you high performance with Zink. The only way to potentially bring performance gains is to use native Vulkan rendering like VulkanMod, and then use Zink for VK<->GL interop to provide compatibility with legacy mods, like [X-Plane](https://www.supergoodcode.com/do-not/).

True, but there is still edge cases technically. Probably could eliminate them if someone cared enough, but they exist technically
https://www.phoronix.com/review/zink-radeon-august2022

**Comment by ColonelGerdauf** [comment]
> Hey, I'd love to see an AMD version of this mod using AMD specific OpenGL extensions too, unfortunately I know little to nothing about graphics programming myself however it is possible to convert OpenGL programs to vulkan using drivers such as zink
> 
> https://www.khronos.org/assets/uploads/developers/presentations/Vulkan-09-Zink-OpenGL-on-Vulkan-SIGGRAPH-Jul19.pdf
> 
> However I also understand if you do not want to work on an AMD port if this mod is tiring enough 😅

I don't think that is possible, given that AMD strictly abides by the original specifications of OpenGL. The AMD-optimized build is… standalone Sodium.

**Comment by nonetrix** [comment]
> > Hey, I'd love to see an AMD version of this mod using AMD specific OpenGL extensions too, unfortunately I know little to nothing about graphics programming myself however it is possible to convert OpenGL programs to vulkan using drivers such as zink
> > https://www.khronos.org/assets/uploads/developers/presentations/Vulkan-09-Zink-OpenGL-on-Vulkan-SIGGRAPH-Jul19.pdf
> > However I also understand if you do not want to work on an AMD port if this mod is tiring enough 😅
> 
> I don't think that is possible, given that AMD strictly abides by the original specifications of OpenGL. The AMD-optimized build is… standalone Sodium.

I would assume this applies to Vulkan too? If not I guess someone could make something like this for the Vulkan Mod https://github.com/xCollateral/VulkanMod but I doubt it's a exception

**Comment by Andarwinux** [comment]
>The OpenGL team has replied that they have plan to support mesh shader for AMD OpenGL driver in the future.
Thanks.

https://community.amd.com/t5/opengl-vulkan/is-mesh-shader-support-planned-for-opengl/m-p/649970/highlight/true#M5068

**Comment by nonetrix** [comment]
Neat, but will something similar be added to RadeonSI/Mesa drivers? Maybe worth mentioning on the Gitlab for Mesa?

**Comment by PeterStrick** [comment]
> Neat, but will something similar be added to RadeonSI/Mesa drivers? Maybe worth mentioning on the Gitlab for Mesa?

Fairly certain if the OpenGL Team has plans to add Mesh Shaders to the OpenGL driver, they will first appear on Mesa and then on Windows

**Comment by nixigaj** [comment]
> Neat, but will something similar be added to RadeonSI/Mesa drivers? Maybe worth mentioning on the Gitlab for Mesa?

Just gonna link this issue here for those interested in this topic: https://gitlab.freedesktop.org/mesa/mesa/-/issues/7192

**Comment by beedell-roke** [comment]
https://github.com/MCRcortex/nvidium/issues/138#issuecomment-1902374971 is a potential solution to this, @lukim007.

**Comment by IGN-Styly** [comment]
We are going to get the opengl function required for this mod in a later opengl version.

**Comment by ImBehinYa** [comment]
I opened an issue in AMD's new driver forum on GitHub and already received a response. They are aiming for the end of the year. Maybe you should comment or react so they see that this matters to us.

https://github.com/GPUOpen-Drivers/AMD-Gfx-Drivers/issues/4

**Comment by Sterophonick** [comment]
The radeonsi driver in Mesa (for Linux/BSD) is getting support for `GL_EXT_mesh_shader` so it might be possible for this mod to get ported over to use that extension instead of the NVIDIA-specific one.

https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/36751

**Comment by Haxorzz** [comment]
So now that the generic OpenGL extension exists, and drivers have implemented it (e.g. mesa), will there be a port of this mod to the vendor-agnostic version?

**Comment by KarmaMarazu** [comment]
> So now that the generic OpenGL extension exists, and drivers have implemented it (e.g. mesa), will there be a port of this mod to the vendor-agnostic version?

work has already begun

**Comment by Haxorzz** [comment]
> > So now that the generic OpenGL extension exists, and drivers have implemented it (e.g. mesa), will there be a port of this mod to the vendor-agnostic version?
> 
> work has already begun

Thank you my goats

**Comment by nonetrix** [comment]
1. 

> > So now that the generic OpenGL extension exists, and drivers have implemented it (e.g. mesa), will there be a port of this mod to the vendor-agnostic version?
> 
> work has already begun

Seperate repo I assume since they said they wouldn't do it in this mod? Has that changed now that we don't have to do it theoretically in hacky ways? If so maybe this should be reopened with "nofix" removed
