### ISSUE TITLE
Add Iris support

### ISSUE THREAD

**Issue by Kirishim-arashi** [MCRcortex/nvidium#44]
I hope can Add Iris support
It's very important , thanks
We need shadows in minecraft

**Comment by Un1q32** [comment]
search other issues before making a new one https://github.com/MCRcortex/nvidium/issues/3 https://github.com/MCRcortex/nvidium/issues/26 https://github.com/MCRcortex/nvidium/issues/32

> The fundamental way this mod works is different to iris, fixing it is very hard and complex, let alone fixing it correctly, perhaps in the future a middle ground can be developed and some support added, however that is not for the foreseeable future

Iris isn't coming anytime soon.

**Comment by ghost** [comment]
its no possible

**Comment by CrabbyDisk** [comment]
It may be possible but the entire codebase of Nvidium and Iris will be rewriten wich will take a signifiant amout of time and effort so it's not comming out significantly soon especially not when it's only one developper working on this.

This issue can now be closed.

**Comment by Lualttt** [comment]
how many times are people gonna ask this again do they not check for the issue before making one?
