### ISSUE TITLE
forge support ?

### ISSUE THREAD

**Issue by x-Haruyuki** [MCRcortex/nvidium#46]
When is Forge supported?

**Comment by ghost** [comment]
no, officially it will not be ported

since sodium is only for fabric

and fabric is better for optimization mods

**Comment by gabe56f** [comment]
Join the discord, in the #rendering channel I've sent a jar file that works with rubidium 0.6.5 (minecraft 1.20.1)

**Comment by EasonCAI1701** [comment]
> Join the discord, in the #rendering channel I've sent a jar file that works with rubidium 0.6.5 (minecraft 1.20.1)

can you sent it in another way?i can not cannet the discord

**Comment by OfficialPixelBrush** [comment]
> Join the discord, in the #rendering channel I've sent a jar file that works with rubidium 0.6.5 (minecraft 1.20.1)

Would you happen to have a version that works for 1.19.2?

**Comment by Oneton429** [comment]
Sodium can be used on Forge now. Hoping this mod could support Forge soon

**Comment by MrCatlio** [comment]
> Sodium can be used on Forge now. Hoping this mod could support Forge soon

you can use connector with forge but you dont see much of a improvement but theres a version of Nvidium called Acedium that works on Forge
