### ISSUE TITLE
Block faces are culled regardless of Sodium's block face culling setting

### ISSUE THREAD

**Issue by forkiesassds** [MCRcortex/nvidium#48]
Additionally if a mod tries to bypass face culling by overriding the bounding box it instead gets ignored and uses it's own render bounding box.

**Comment by forkiesassds** [comment]
Nvidium seems to bypass DefaultChunkRenderer.getVisibleFaces (Sodium 0.5.2+) and RegionChunkRenderer.buildDrawBatches (Sodium 0.4.x)

**Comment by MCRcortex** [comment]
fixed in https://github.com/MCRcortex/nvidium/commit/94508e3884f72b94d4d6030548e4a7bb425a690c
