### ISSUE TITLE
ground sometimes stops rendering when you mine down

### ISSUE THREAD

**Issue by The-Nyla** [MCRcortex/nvidium#5]
![image](https://user-images.githubusercontent.com/79489385/233215006-d278ded7-04d1-4bcc-a964-cb725a36cb9c.png)
The ground resumes rendering correctly when you aren't standing on it

**Comment by MCRcortex** [comment]
does it stop completly or flicker?

**Comment by The-Nyla** [comment]
It flickers rapidly

**Comment by MCRcortex** [comment]
Fixed in https://github.com/MCRcortex/nvidium/commit/52b1e5d6ca8004f4284d7b3af579c2f3d0af9326
