### ISSUE TITLE
alt tabbing while in fullscreen freeze the game

### ISSUE THREAD

**Issue by diarm56** [MCRcortex/nvidium#50]
as the title say the game freeze while alt tabbing while being in fullscreen.
Does not happen when the game is windowed.

reproduction step:

Launch the game, put it in fulscreen, lauch a save, alt tab and boom.

The game seems to still be rendering. there is still report of load in HWInfo and sound still play.
but the game render a still image of the last frame rendered

Laucher : Prisme Launcher

OS : windows 11 22H2

nvidia RTX3080 536.40

minecraft 1.20.1

only Sodium 0.4.10 and nvidium 0.1.14

latest log:
[latest.log](https://github.com/MCRcortex/nvidium/files/12032352/latest.log)

**Comment by AMDKilla** [comment]
As far as I'm aware, thats default Minecraft behavior in fullscreen on Java in singleplayer. Multiplayer continues in the background. It's only in Bedrock where the singleplayer continues.
