### ISSUE TITLE
Port for GTX 10 series

### ISSUE THREAD

**Issue by iDkGK** [MCRcortex/nvidium#54]
Could you please make it compatible with GTX 10 series graphicscard? Running game on my laptop with GTX1060, I found the mod won't work.
If not, could you please explain why it cannot work on GTX1060?

**Comment by Un1q32** [comment]
The mod requires extensions to OpenGL that weren't added until the 16xx and 20xx cards.

**Comment by iDkGK** [comment]
> 

Got it. That's such a pity. I think it's time to upgrade my hardware :(
Anyway, thanks for your explanation dude.
