### ISSUE TITLE
Glass rendering is incorrect on chunk boundaries

### ISSUE THREAD

**Issue by 1upbyte** [MCRcortex/nvidium#55]
Without Nvidium
![2023-07-24_15 31 03](https://github.com/MCRcortex/nvidium/assets/55856800/3f1aa14b-b7ae-4e01-be02-67d290c80028)

With Nvidium
![2023-07-24_15 32 03](https://github.com/MCRcortex/nvidium/assets/55856800/c63cd783-ed7a-4d68-acbb-5bf046f6e583)

Can provide additional files (logs, mods, etc) if needed.

**Comment by MCRcortex** [comment]
As of nvidium 0.2.3-beta, there is translucency sorting and this should no longer be an issue
