### ISSUE TITLE
Honey blocks do not render correctly in-world

### ISSUE THREAD

**Issue by sisby-folk** [MCRcortex/nvidium#59]
![javaw_15MR1MN3r7](https://github.com/MCRcortex/nvidium/assets/55819817/2592c2b7-a7b4-414e-859d-15e6b5fd05a3)

Quilt 1.20.1, 0.1.15

in hand and in inventory they're fine.

**Comment by MCRcortex** [comment]
Translucency sorting issue, known issue, unfortunalty insanly hard to fix

**Comment by MCRcortex** [comment]
As of nvidium 0.2.3-beta, there is translucency sorting and this should no longer be an issue
