### ISSUE TITLE
JVM Crash when joining on a Server

### ISSUE THREAD

**Issue by Lenni0451** [MCRcortex/nvidium#60]
When joining a server the JVM sometimes crashes. This happens ever 1-3 days and is never consistent.

JVM crash dump: https://haste.lenni0451.net/ajohamesat.yaml
Nvidium Version: 0.1.15-alpha

**Comment by hexadecimal233** [comment]
It crashes, but different Problematic frame:
`# J 46880 c2 me.cortex.nvidium.managers.RegionVisibilityTracker.lambda$computeVisibility$0([SJ)V (71 bytes) @ 0x0000022d91ccd985 [0x0000022d91ccd8a0+0x00000000000000e5]`
