### ISSUE TITLE
Sky doesn't render properly

### ISSUE THREAD

**Issue by SirenGlitch** [MCRcortex/nvidium#62]
The top half of the world is fine, bottom half is like if you turned off sky rendering.
# Server example
![image](https://github.com/MCRcortex/nvidium/assets/110285018/ee5d81f2-c8ba-4cdf-847c-636f3258fd86)

# Singleplayer example
![image](https://github.com/MCRcortex/nvidium/assets/110285018/7ff4c9e9-2622-4827-863c-7af968641b3d)

**Comment by BenPerkins-HunterOrbit** [comment]
This happens with Region Keep Distances greater than 32 right? I just opened this https://github.com/MCRcortex/nvidium/issues/151

**Comment by SirenGlitch** [comment]
> This happens with Region Keep Distances greater than 32 right? I just opened this #151

Judging by the fact that you have the same issue, then Yes, most likely

**Comment by KarmaMarazu** [comment]
#160
