### ISSUE TITLE
Excessive memory allocations

### ISSUE THREAD

**Issue by MCRcortex** [MCRcortex/nvidium#64]
Something is causing exessive memory allocations that are not in base sodium when loading new chunks

**Comment by REALERvolker1** [comment]
Can corroborate. The included log shows this when I press and hold F3 + A. Fortunately it only left me with a slightly shidded X server afterwards but others might not be as lucky. https://mclo.gs/JjZqZmi

Using RTX 3060 Mobile / Max Q with drivers 535.129.03 on Fedora Linux
