### ISSUE TITLE
Incompatible with newer versions of Sodium

### ISSUE THREAD

**Issue by TheobaldTheBird** [MCRcortex/nvidium#65]
Requires outdated versions of Sodium to run, e.g. can't run it with Sodium 0.5.0

**Comment by QPCrummer** [comment]
There is a branch for sodium 0.5, however when I ran it I experienced extreme graphical glitches and flickering. It may be just me, but in terms of performance it was fantastic!

**Comment by tr7zw** [comment]
Yea can confirm, currently some slight glitches, but god damn(16 chunk distance).
![grafik](https://github.com/MCRcortex/nvidium/assets/5133936/0b55ce03-3e18-4f23-83b6-540a9f267efc)
1000+ with 32.
Amazing job MCRcortex.

**Comment by Un1q32** [comment]
https://cdn.discordapp.com/attachments/973046939375505411/1137364612002627594/nvidium_tmp-0.1.16-alpha.jar
this is a build cortex posted in the discord, works well for me

**Comment by QPCrummer** [comment]
That build didn't fix my issue. Here is a video that demonstrates it:

https://github.com/MCRcortex/nvidium/assets/66036033/0a5d4858-7da7-45a2-8e4b-2ec0cfc35327

**Comment by Un1q32** [comment]
maybe dont use java 21 beta, use java 17

**Comment by QPCrummer** [comment]
The Java version used should not matter as it was working fine with the last release of Nvidium. Also a newer Java versions tends to not break mods. If a breakage does occur, the game would've most likely crashed. You can actually run 1.12.2 modpacks on Java 21 and they work perfectly fine.

**Comment by ghost** [comment]
> The Java version used should not matter as it was working fine with the last release of Nvidium. Also a newer Java versions tends to not break mods. If a breakage does occur, the game would've most likely crashed. You can actually run 1.12.2 modpacks on Java 21 and they work perfectly fine.

and how to make 1.12.2 forge work with java version above 8 ?

**Comment by Ange8B** [comment]
guys i have tried this nvidium jar with a fork of bobby made to be compatible with sodium 0.5  and this bug seems gone (idk why) but nvidium keep culling some random chuncks while playing (when I update them they became visible but I have to update them one by one) the culling should happen only with the option enabled but this bug happen even if it is disabled.  

![Screenshot 2023-08-07 193506](https://github.com/MCRcortex/nvidium/assets/141659066/d9ef7f14-182c-4b46-a94b-a98ae374f6ef)

**Comment by Ange8B** [comment]
> That build didn't fix my issue. Here is a video that demonstrates it:
> 
>  VisualGlitches.mp4

referring to this (i forgot to reply)

**Comment by Inconn** [comment]
![image](https://github.com/MCRcortex/nvidium/assets/62788103/9cc66036-5b2d-4b90-8f3a-68fa7662e32f)
nvidium on sodium 0.5 works fine for me except for if i look at a certain direction, it makes the clouds render through everything, like the screenshot shows.
i removed the mod and it didn't happen.

**Comment by Inconn** [comment]
for the record, this is on java 21-ea and on linux
