### ISSUE TITLE
NVIDIA Drivers Version 536.67 and higher causes STACK_BUFFER_OVERRUN / Exitcode -1073740791 Crash

### ISSUE THREAD

**Issue by asoji** [MCRcortex/nvidium#66]
# Problem

After a lot of testing with @MCRcortex on Windows 10 [from 522.30 to 536.99, Studio variant, also known with Game Ready variant], and 1 driver version [536.67] on Windows 11, we have nailed down that 536.67 and higher are prone to `STACK_BUFFER_OVERRUN`/`Process crashed with exitcode -1073740791` crashes in unknown circumstances. From what @MCRcortex knows, this seems to be the exact same issue Sodium devs have been experiencing, specifically CaffeineMC/sodium-fabric#1816 and CaffeineMC/sodium-fabric#1486 who have been running into the same issues with NVIDIA's own OpenGL hacks. 

We don't know what mods seem to be potentially conflicting with Nvidium to get this to happen too, because when tested in a singleplayer environment, it doesn't seem to want to crash, but in a particular server environment with a lot of modded block content, after a bit of minimizing the game and maximising and clicking in and out of the game window, it will eventually hang and then crash. No JVM crash log will generate, or a game crash log. Basically as if the OS has quit its own process.

# Potential Solutions

Currently, none known, but anything 536.40 and under *seem* to be unaffected? I couldn't seem to get the game to crash at all on those older versions.

# Initial Testing System
OS: Windows 11 Pro for Workstations - Version 22H2 [OS Build 22621.2134]
CPU: AMD Ryzen 5 5600x
GPU: GIGABYTE NVIDIA RTX 3070ti VISION OC V2
GPU Driver: NVIDIA Studio Drivers v536.67 / 31.0.15.3667 7/12/2023
NVIDIA System Information: [link removed]
JVM: Eclipse Termurin Build 17.0.5+8 / openjdk 17.0.5 22-10-18

**Comment by TheoCGaming** [comment]
maybe this could have something to do with OpenGL losing context? It's a wild guess out of nowhere I know, but I've been having frequent issues with OpenGL/WebGL losing context on my laptop with Radeon graphics, and my main PC's also been having issues with OpenGL contexts when it's been left on for too long.

**Comment by MCRcortex** [comment]
Havent run into this issue ever since and people should have updated there graphics drivers by now ™️
