### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by LiviiYS** [MCRcortex/nvidium#68]
Smoke renders from campfire under the ground when you tilt camera to certain positions

![2023-08-18_19 11 32](https://github.com/MCRcortex/nvidium/assets/72738254/881c37d1-2690-4194-aacb-7257a08050cc)
![2023-08-18_19 13 39](https://github.com/MCRcortex/nvidium/assets/72738254/821e5a91-fe01-4042-a39c-70c8424330c5)

**Comment by MCRcortex** [comment]
This issue should no longer occur, please reopen the issue if it persists
