### ISSUE TITLE
Crash on world join

### ISSUE THREAD

**Issue by MidyGamy** [MCRcortex/nvidium#69]
So my game crashes whenever I join a singleplayer or multiplayer world

[latest.log](https://github.com/MCRcortex/nvidium/files/12378558/latest.log)
[crash-2023-08-18_13.02.08-client.txt](https://github.com/MCRcortex/nvidium/files/12378560/crash-2023-08-18_13.02.08-client.txt)

**Comment by BuggyAl** [comment]
There are about a thousand lines of errors from various mods. I would probably do the following:

1. Remove mods until you find the problematic mod
2. Test Nvidium with that mod alone
3. Send a crash log with that mod alone
