### ISSUE TITLE
clear water and glass

### ISSUE THREAD

**Issue by thisntdame** [MCRcortex/nvidium#72]
![2023-08-29_17 40 39](https://github.com/MCRcortex/nvidium/assets/143525598/113de8f8-5df0-4537-9794-b1d6f3f413d1)
![2023-08-29_17 40 50](https://github.com/MCRcortex/nvidium/assets/143525598/9900fdbb-e313-466d-a104-b8d986eb33d7)

**Comment by MCRcortex** [comment]
If this is still an issue with the latest nvidium release please reopen the issue
