### ISSUE TITLE
Blocks dont render at a high distance from 0 0.

### ISSUE THREAD

**Issue by Grisu-FTP** [MCRcortex/nvidium#73]
The first screenshot where everything renders is without and the 2nd with nvidium. everything that isnt an entity stops rendering completly.
![image](https://github.com/MCRcortex/nvidium/assets/69594916/00d575fd-120a-411c-8db7-89e239c1ed55)
![image](https://github.com/MCRcortex/nvidium/assets/69594916/0f19c294-5f0e-4ab7-91fd-916ed6f8a916)
The world still has collision and everything apart from rendering works like expected.

**Comment by thelampgod** [comment]
this is still an issue, any update on when this might get fixed?

**Comment by MCRcortex** [comment]
hopefully in the next update 0.2.1
