### ISSUE TITLE
Server Side plz

### ISSUE THREAD

**Issue by Colorflow-exe** [MCRcortex/nvidium#79]
I Very Need it

**Comment by Leung288** [comment]
I Very Need it

**Comment by Andarwinux** [comment]
What can a render optimization mod do on the server side?

**Comment by Un1q32** [comment]
> What can a render optimization mod do on the server side?

It will speed up server side rendering, obviously

**Comment by Andarwinux** [comment]
Does the server side need to render anything?

**Comment by Un1q32** [comment]
It renders the server

**Comment by emortaldev** [comment]
For map rendering of course

**Comment by Bipbip2109** [comment]
This is the most retarded github post I've ever seen and this is amazing
