### ISSUE TITLE
Chunks are visible on ice 0.2 Beta

### ISSUE THREAD

**Issue by Redtendo22** [MCRcortex/nvidium#82]
![2023-09-25_21 13 53](https://github.com/MCRcortex/nvidium/assets/116605206/95f2dfe4-fe6a-474e-b669-65bbe3cff6f1)

**Comment by MikiP98** [comment]
This is a duplicate of #9

**Comment by PFnove** [comment]
you need to set "Translucency Sorting" to Sections or Quads
