### ISSUE TITLE
Entities don't render 

### ISSUE THREAD

**Issue by Kusel42** [MCRcortex/nvidium#85]
Zombies, Villagers, and minecarts aren't rendered in. I am not sure about other entities.
This is on multiplayer

![nvidium bug](https://github.com/MCRcortex/nvidium/assets/79448324/050c9974-1c2e-4646-b858-1b9bbc846a38)
![nvidium bug1](https://github.com/MCRcortex/nvidium/assets/79448324/b83cd035-5441-4db0-958e-e7e52549c363)

**Comment by MCRcortex** [comment]
are you on nvidium 0.2.1?

**Comment by Kusel42** [comment]
no, I am playing on 1.19.4

**Comment by MCRcortex** [comment]
this issue is fixed in newer nvidium releases, please update
