### ISSUE TITLE
[suggestion/request] Would be greatly appreciated if there are more backports

### ISSUE THREAD

**Issue by Aabyonis** [MCRcortex/nvidium#86]
title pretty much sums it up, would be great to have ports to versions like 1.19.2 and 1.18.X mainly because of the availability of mods. love this performance mod and how greatly it improves performance, keep up the great job!

**Comment by Minepolz320** [comment]
1.7.10 will blow up like nuke under this mod xD

**Comment by PlayfulPiano** [comment]
Supporting this as well. Considering that sodium also had a lot of personal optimizations in v0.5 that's exclusive to mc1.20, nvidium would be a great alternative performance booster for players still on 1.18.x or 1.19.x.

**Comment by GamerTable** [comment]
The issue with this is that Nvidium depends on Sodium .5, 
So this is more of a matter of getting that sodium version backported
