### ISSUE TITLE
Rendering problem with ice and water

### ISSUE THREAD

**Issue by Yoghurted** [MCRcortex/nvidium#9]
A visual defect appears at the borders of the chunks. This happens when ice is placed right on top of water. 
Here is a screenshot of a flat world _(minecraft:bedrock,minecraft:stone,minecraft:water,minecraft:ice;minecraft:plains)_ : 

https://i.postimg.cc/P59M8YNq/Minecraft-Screenshot-2023-04-23-17-04-27-78.png

**Comment by MikiP98** [comment]
![obraz_2023-09-25_180358171](https://github.com/MCRcortex/nvidium/assets/79966387/fe764f49-3a89-47f8-aec7-7a665850a49c)

**Comment by zlatkoxf** [comment]
![2023-10-21_17 28 26](https://github.com/MCRcortex/nvidium/assets/140588476/38ee216d-112c-46fc-9c9f-41ae75fb0bbd)
![2023-10-21_17 37 25](https://github.com/MCRcortex/nvidium/assets/140588476/1e1c5d03-2154-4e9e-a50e-44573b15a1d6)
![2023-10-21_17 36 01](https://github.com/MCRcortex/nvidium/assets/140588476/8b544292-8743-47bb-945b-8d3e1daa6ef8)
+

**Comment by Polarite** [comment]
same problem happens with colored glass as well if placed in a large area

**Comment by MCRcortex** [comment]
As of nvidium 0.2.3-beta, there is translucency sorting and this should no longer be an issue

**Comment by zeid0ne** [comment]
same problem with v0.2.9-beta (in minecraft 1.21)

**Comment by CoolAid48** [comment]
It will be fixed for good with the next Sodium beta release for 0.6.0 First beta should be out by next week according to JellySquid, and I assume a compatible NVIDIUM version will be out soon after :D
