### ISSUE TITLE
Nvidium is incompatible with BCLib

### ISSUE THREAD

**Issue by HLVNHLV** [MCRcortex/nvidium#90]
As the title says, they are both incompatible

**Comment by HLVNHLV** [comment]
I summited the report by error, but here is the TL;DR

BCLib is a dependency for Better End, the thing is that when both mods are installed, in the Nether, there is some kind of "near fog" or something, it's like a sphere of a couple chunks in wich anything inside just does not render properly

![2023-10-21_11 28 34](https://github.com/MCRcortex/nvidium/assets/57480914/0496031f-46e5-44f2-942e-61db8f4a8b62)

https://modrinth.com/mod/bclib

**Comment by MCRcortex** [comment]
what version of nvidium are you using and do you have the region keep distance set to > 119

**Comment by HLVNHLV** [comment]
The active mods for reproducing the issue are the following:

Nvidium 0.1.15-alpha
Fabric API 0.87.1+1.19.4
BCLib 2.3.4

![2023-10-21_11 32 40](https://github.com/MCRcortex/nvidium/assets/57480914/9a357c20-8629-4948-8796-bbc2f68c7841)

**Comment by MCRcortex** [comment]
ah that would be why, these are issues in nvidium 0.1.16 and older, unfortunatly backporting fixes is not something i have time for due to keeping up with sodium versioning (sodium 0.5.3 changed alot compared to 0.4.10)

**Comment by HLVNHLV** [comment]
hmmm so that's the issue, thanks, I used Prism Launcher for downloading it, I suposse that It cannot fetch the latest version or maybe it's not even supported for 1.19.4, but anyways, thanks
