### ISSUE TITLE
crashes with vivecraft at random points

### ISSUE THREAD

**Issue by fayer3** [MCRcortex/nvidium#91]
so, not sure what exactly happens, but with vivecraft we render the world multiple times per frame, once per viewpoint.
if we do that the game crashes at random points, with an `The NVIDIA OpenGL driver has encountered an out of memory error` error.
when only one pass renders, it seems fine.
system ram and gpu ram don't look like they are anywhere near the limit in taskmanager, so no clue why that happens.
it is very easy to provoke the crash at  32 render distance, with vivecrafts resolution scale set to 900%, which roughly equals a 6k*6k resolution
using a 4080 with driver 536.40, but someone else also reported it with a 3070ti and driver 545.84
happens with both 1.20.1 and 1.20.2 on both betas

for reference, this is where we call the render
https://github.com/Vivecraft/VivecraftMod/blob/f061f977325aa2dcedee974802cef7f0560a676f/common/src/main/java/org/vivecraft/client_vr/render/helpers/VRPassHelper.java#L30

and this is where that is called, that happens after the regular GameRenderer.render call, if that matters
https://github.com/Vivecraft/VivecraftMod/blob/f061f977325aa2dcedee974802cef7f0560a676f/common/src/main/java/org/vivecraft/mixin/client_vr/MinecraftVRMixin.java#L462

**Comment by MCRcortex** [comment]
Should be fixed as of 0.2.4-beta, however there are some rendering glitches still due to the multi viewport rendering
