### ISSUE TITLE
Does this work with the Geforce MX450 gpu?

### ISSUE THREAD

**Issue by ISE9218** [MCRcortex/nvidium#93]

**Comment by diarm56** [comment]
in theory yes. it's turing architecture. [best try it and see](https://tryitands.ee/)

**Comment by Sierraint** [comment]
Well i don't think so, mesh shaders are dx 12_2 feature set, and mx450 is only dx12_1, but i also would like to know if it works with turing gpus that are 12_1

**Comment by TukangM** [comment]
I have tested 2 laptops with mx330, and mx230. nvidium doesn't load either

**Comment by Sierraint** [comment]
> I have tested 2 laptops with mx330, and mx230. nvidium doesn't load either

It doesn't work since both of these GPUs are of pascal architecture, and don't have any mesh shaders, turing has mesh shaders built into it's architecture and since mx450 is on turing it should work with Nvidium
