### ISSUE TITLE
Any stained glass makes water disappear

### ISSUE THREAD

**Issue by Ivanmatthew** [MCRcortex/nvidium#94]
Any type of stained glass makes the water fully disappear, making players be able to view inside the water akin to having the night vision effect (minus water textures).

Without nvidium enabled:
![2023-10-24_20 04 19](https://github.com/MCRcortex/nvidium/assets/76107136/fee2db98-6aca-4546-866a-85bca0e2b959)

With nvidium enabled:
![2023-10-24_20 03 47](https://github.com/MCRcortex/nvidium/assets/76107136/754aa3fc-b2e9-4cf6-92b5-b4ae9ec48313)

Mod list:
<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yosbr">Your Options Shall Be Respected (YOSBR) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/entity-model-features">[EMF] Entity Model Features [Fabric & Forge] (by traben_0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-chat-history">More Chat History (by JackFred2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/puzzle">Puzzle (by Motschen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dynamic-fps">Dynamic FPS (by juliand665)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/language-reload">Language Reload (by Jerozgen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cit-resewn">CIT Resewn (by SHsuperCM)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/capes">Capes [Fabric/Forge] (by VictorKohler)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin">Fabric Language Kotlin (by modmuss50)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/advancementinfo">AdvancementInfo (by Giselbaer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabrishot">Fabrishot (by ramidzkh)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/lithium">Lithium (Fabric) (by jellysquid3_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/borderless-mining">Borderless Mining (by comp500)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/lambdynamiclights">LambDynamicLights (by LambdAurora)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fadeless">Fadeless (by DerpDerpling)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/indium">Indium (by comp500)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/debugify">Debugify (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/chat-reporting-helper">Chat Reporting Helper (by robotkoer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabric-api">Fabric API (by modmuss50)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/zoomify">Zoomify (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yacl">YetAnotherConfigLib (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mixintrace">MixinTrace (by comp500)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/controlify">Controlify (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-mount-hud">Better Mount HUD (by Lortseam_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/optigui">OptiGUI (by opekope2)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sodium-extra">Sodium Extra (by FlashyReese)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/immediatelyfast">ImmediatelyFast (by RaphiMC)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/model-gap-fix">Model Gap Fix (by MehVahdJukaar)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/continuity">Continuity (by Pepper_Bell)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric">FerriteCore (Fabric) (by malte0811)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/main-menu-credits">Main Menu Credits (by XanderIsDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fastquit">FastQuit (by KingContaria)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/fast-better-grass">Fast Better Grass (by robotkoer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/e4mc">e4mc (by skyegreen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rrls">Remove Reloading Screen (by dimadencep)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/entityculling">Entity Culling Fabric/Forge (by tr7zw)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options">Reese's Sodium Options (by FlashyReese)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/modernfix">ModernFix (by embeddedt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/no-chat-reports">No Chat Reports (by Aizistral)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric">[ETF] Entity Texture Features - [Fabric & Forge] (by traben_0)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabricskyboxes">FabricSkyboxes (by AMereBagatelle)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/fabricskyboxes-interop">FabricSkyBoxes Interop (by FlashyReese)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities">Enhanced Block Entities (by FoundationGames)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/translations-for-sodium">Translations for Sodium (by robotkoer)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/animatica">Animatica (by FoundationGames)</a></li>
</ul>

**Comment by radarcorr** [comment]
Try removing CIT Resewn it causes the majority of the bugs i encounter

**Comment by Ivanmatthew** [comment]
> Try removing CIT Resewn it causes the majority of the bugs i encounter

I can unfortunately confirm that, even with CIT Resewn removed, the same issue persists.

**Comment by MCRcortex** [comment]
this is translucency, there will be an option enabled by default to fix this and other issues like it in the next update
