### ISSUE TITLE
Client Crash when TP'd on a server in 1.20.2

### ISSUE THREAD

**Issue by kindalas** [MCRcortex/nvidium#96]
Just updated to the latest version of Nvidium, and when I have discovered that when I am teleported by a command block on a 100% vanilla server the client will crash.

I have included my crash report.

[crash-2023-10-27_15.43.47-client.txt](https://github.com/MCRcortex/nvidium/files/13192828/crash-2023-10-27_15.43.47-client.txt)

**Comment by TH3N3WN00B** [comment]
Please paste your crash report [here](https://mclo.gs/) and update this issue with new link

**Comment by kindalas** [comment]
Here is the link to the crash report using the link above.


https://mclo.gs/VYIrFTS

**Comment by gxjakkap** [comment]
Also facing this. 

Here's my logs.
https://mclo.gs/55p5eZW

I tried disabling Sodium Extras, Reese's Sodium Option, Indium, Continuity to no avail.

**Comment by gxjakkap** [comment]
I tried isolating the mods and run with just Fabric API + Sodium + Nvidium and it still crashes. The difference being that it doesn't crash on the first command but it does on the second time.

https://mclo.gs/0BjBQxT

**Comment by MCRcortex** [comment]
the current "fix" is to just increase your frame ahead value in sodium, i will push a proper fix when i get time
