### ISSUE TITLE
Block raycasts are limited to render distance

### ISSUE THREAD

**Issue by RXJpaw** [MCRcortex/nvidium#97]
`net.minecraft.world.BlockView#raycast(RaycastContext)` will not reach blocks in chunks outside the real render distance.
I expected "terrain geometry" to mean that raycasts would hit actual blocks. Is there a raycast implementation planned?

**Comment by MCRcortex** [comment]
The nvidium terrain lives only in gpu memory, minecraft does not know of its existence.
Any terrain outside the default render distance gets unloaded, nvidium just keeps the built chunk meshes on the gpu
