### ISSUE TITLE
Can't control player with Nvidium installed

### ISSUE THREAD

**Issue by Evilrymon** [MCRcortex/nvidium#98]
After installing Nvidium, I can navigate the main menu, but as soon as a world loads, my mouse appears, and I cannot look, move, or open any menus. It is not that Minecraft isn't selected, alt+F4 still closes Minecraft in specific (and other than task manager is the only way to close the game). I have a Nvidia GeForce RTX 2070 and thus it should run perfectly fine, I don't know why it would just stop giving my player control.

**Comment by GamingWithDudeAlt** [comment]
Remove Fastload and replace it with Ksyxis if you have Fastload installed. This sounds exactly like the issue Fastload has that I don't think will ever be fixed. Ksyxis does the same thing exact thing, only it doesn't suffer from this issue. Ksyxis in my experience loads the world ever so slightly faster than Fastload too.

**Comment by Evilrymon** [comment]
Thank you, this worked, much appreciated!

**Comment by Matthew-MBG** [comment]
I fix it with Essential by taking a screenshot, and then hitting the edit button
